import type { TranslationKeys } from './en';
const bn: TranslationKeys = {
  nav: { home: 'হোম', seedGuide: 'বীজ গাইড', weather: 'আবহাওয়া', aiTools: 'AI টুলস', farmManagement: 'খামার ব্যবস্থাপনা', community: 'সম্প্রদায়', sos: 'SOS', contact: 'যোগাযোগ', login: 'লগইন', signup: 'সাইন আপ', logout: 'লগআউট', aiDecisionEngine: '🧠 AI সিদ্ধান্ত ইঞ্জিন', voiceAssistant: '🎙️ ভয়েস অ্যাসিস্ট্যান্ট', profitPrediction: '📈 মুনাফা পূর্বাভাস', diseaseScanner: '🔬 রোগ স্ক্যানার', expenseTracker: '💰 ব্যয় ট্র্যাকার', iotMonitoring: '📡 IoT পর্যবেক্ষণ', digitalTwin: '🗺️ ডিজিটাল টুইন', farmerCommunity: '💬 কৃষক সম্প্রদায়', marketplace: '🛒 বাজার', govtSchemes: '🏛️ সরকারি প্রকল্প', learningHub: '📚 শিক্ষা কেন্দ্র', emergencySOS: '🚨 জরুরি SOS', switchTheme: 'থিম পরিবর্তন' },
  hero: { badge: 'স্মার্ট কৃষি প্ল্যাটফর্ম', title1: 'স্মার্ট চাষ করুন,', title2: 'ভালো ফসল কাটুন', description: 'AgriAssist আপনার মাঠে অত্যাধুনিক প্রযুক্তি নিয়ে আসে।', getStarted: 'শুরু করুন', exploreFeatures: 'বৈশিষ্ট্য দেখুন', yieldIncrease: 'ফলন বৃদ্ধি', costReduction: 'খরচ হ্রাস', monitoring: 'পর্যবেক্ষণ' },
  features: { badge: 'শক্তিশালী বৈশিষ্ট্য', title: 'স্মার্ট চাষের জন্য সবকিছু', subtitle: 'আমাদের প্ল্যাটফর্ম AI, IoT এবং ডেটা বিশ্লেষণ একত্রিত করে।' },
  cta: { title: 'আপনার চাষ পরিবর্তন করতে প্রস্তুত?', subtitle: 'হাজার হাজার কৃষকের সাথে যোগ দিন যারা AgriAssist ব্যবহার করছেন।', startTrial: 'বিনামূল্যে ট্রায়াল শুরু করুন', scheduleDemo: 'ডেমো নির্ধারণ করুন' },
  weather: { title: 'কৃষি আবহাওয়া পূর্বাভাস', subtitle: 'কৃষি-নির্দিষ্ট অন্তর্দৃষ্টি সহ রিয়েল-টাইম আবহাওয়া ডেটা', searchPlaceholder: 'শহর বা অবস্থান অনুসন্ধান করুন...', current: 'বর্তমান', forecast: 'পূর্বাভাস', calendar: 'ক্যালেন্ডার', humidity: 'আর্দ্রতা', wind: 'বায়ু', pressure: 'চাপ', visibility: 'দৃশ্যমানতা', sunrise: 'সূর্যোদয়', sunset: 'সূর্যাস্ত', feelsLike: 'অনুভব হয়', uvIndex: 'UV সূচক', dewPoint: 'শিশির বিন্দু', rainfall: 'বৃষ্টিপাত', farmingAdvisory: 'আজকের কৃষি পরামর্শ', noAlerts: 'কোনো সক্রিয় সতর্কতা নেই', weatherAlert: 'আবহাওয়া সতর্কতা', forecastTitle: '১৪-দিনের পূর্বাভাস', goodFarmDays: 'ভালো চাষের দিন', rainyDays: 'বৃষ্টির দিন', avgTemp: 'গড় তাপমাত্রা', avgHumidity: 'গড় আর্দ্রতা' },
  marketplace: { badge: 'কৃষক বাজার', title: 'ফার্ম মার্কেটপ্লেস ও সম্পদ ভাগাভাগি', subtitle: 'বীজ, সরঞ্জাম, যন্ত্রপাতি কিনুন/বিক্রি করুন।', searchPlaceholder: 'বীজ, সরঞ্জাম, ট্র্যাক্টর, শ্রমিক অনুসন্ধান করুন...', allCategories: 'সব বিভাগ', seeds: 'বীজ', tools: 'সরঞ্জাম', equipment: 'যন্ত্রপাতি', labor: 'শ্রমিক', tractorRental: 'ট্র্যাক্টর ভাড়া', postListing: 'তালিকা পোস্ট করুন', chatWhatsApp: 'WhatsApp-এ চ্যাট করুন', contactSeller: 'বিক্রেতার সাথে যোগাযোগ করুন', soldOut: 'বিক্রি হয়ে গেছে', whatsappAvailable: 'WhatsApp উপলব্ধ', postNewListing: 'নতুন তালিকা পোস্ট করুন', productName: 'পণ্য / সেবার নাম', category: 'বিভাগ', price: 'মূল্য', unit: 'একক / মেয়াদ', sellerName: 'আপনার নাম / দোকানের নাম', location: 'অবস্থান', whatsappNumber: 'WhatsApp মোবাইল নম্বর', description: 'বিবরণ', productImage: 'পণ্যের ছবি', cancel: 'বাতিল করুন', postWithWhatsApp: 'WhatsApp দিয়ে পোস্ট করুন', listingPosted: 'তালিকা পোস্ট হয়েছে!', noListings: 'কোনো তালিকা পাওয়া যায়নি।' },
  seedGuide: { badge: 'বীজ গাইড', title: 'আপনার খামারের জন্য সঠিক বীজ খুঁজুন', subtitle: 'বিভিন্ন অঞ্চল, মাটি এবং জলবায়ুর জন্য অপ্টিমাইজড বীজের সংগ্রহ দেখুন।', recommendations: 'সুপারিশ', calculator: 'বীজ ক্যালকুলেটর', catalog: 'সম্পূর্ণ ক্যাটালগ', searchPlaceholder: 'বীজ অনুসন্ধান করুন...', season: 'মৌসুম', allSeasons: 'সব মৌসুম', clearFilters: 'ফিল্টার পরিষ্কার করুন', noSeeds: 'আপনার মানদণ্ড অনুযায়ী কোনো বীজ পাওয়া যায়নি।', fullCatalog: '🌱 সম্পূর্ণ ক্যাটালগ – বীজ গাইড', catalogSubtitle: 'আপনার সব কৃষি প্রয়োজনের জন্য বীজের সম্পূর্ণ সংগ্রহ', vegetables: '১. সবজি', fruits: '২. ফল', flowers: '৩. ফুল', fieldCrops: '৪. মাঠ ফসল', growthDuration: 'বৃদ্ধির সময়কাল', climateSoil: 'জলবায়ু/মাটি', yieldPotential: 'ফলন সম্ভাবনা', careTips: 'যত্নের টিপস' },
  ai: { badge: 'AI-চালিত বুদ্ধিমত্তা', title: 'AI ফার্ম সিদ্ধান্ত ইঞ্জিন', subtitle: 'আপনার খামারের বিবরণ পূরণ করুন এবং সম্পূর্ণ ফার্ম রিপোর্ট পান।', farmConditions: 'খামারের অবস্থা', cropType: 'ফসলের ধরন', soilType: 'মাটির ধরন', cropStage: 'ফসলের পর্যায়', season: 'মৌসুম', irrigationSource: 'সেচের উৎস', stateRegion: 'রাজ্য / অঞ্চল', farmArea: 'খামারের আয়তন (একর)', temperature: 'তাপমাত্রা', soilMoisture: 'মাটির আর্দ্রতা', generateReport: 'সম্পূর্ণ ফার্ম রিপোর্ট তৈরি করুন', readyToAnalyze: 'বিশ্লেষণের জন্য প্রস্তুত', readySubtitle: 'AI-চালিত অন্তর্দৃষ্টির জন্য খামারের অবস্থা পূরণ করুন।', cropOverview: 'ফসলের সংক্ষিপ্ত বিবরণ ও মূল তথ্য', irrigationPlan: 'সেচ পরিকল্পনা', fertilizerSchedule: 'সার সময়সূচি', pestRisk: 'কীটপতঙ্গ ও রোগ ঝুঁকি মূল্যায়ন', weeklyPlan: '৭-দিনের কর্ম পরিকল্পনা', profitEstimate: 'মুনাফা ও রাজস্ব অনুমান', govtSchemes: 'প্রাসঙ্গিক সরকারি প্রকল্প', aiGenerated: 'AI জেনারেটেড', missingFields: 'অসম্পূর্ণ ক্ষেত্র', missingFieldsDesc: 'অনুগ্রহ করে ফসল, মাটি, পর্যায় এবং মৌসুম পূরণ করুন।', reportReady: 'ফার্ম রিপোর্ট প্রস্তুত' },
  common: { loading: 'লোড হচ্ছে...', search: 'অনুসন্ধান', filter: 'ফিল্টার', submit: 'জমা দিন', cancel: 'বাতিল', save: 'সংরক্ষণ', delete: 'মুছুন', edit: 'সম্পাদনা', close: 'বন্ধ', back: 'পিছনে', next: 'পরবর্তী', previous: 'পূর্ববর্তী', viewAll: 'সব দেখুন', learnMore: 'আরও জানুন', getStarted: 'শুরু করুন', required: 'প্রয়োজনীয়', optional: 'ঐচ্ছিক', yes: 'হ্যাঁ', no: 'না', high: 'উচ্চ', medium: 'মাঝারি', low: 'কম', excellent: 'চমৎকার', good: 'ভালো', fair: 'মোটামুটি', poor: 'খারাপ' },
  footer: { tagline: 'AI-চালিত অন্তর্দৃষ্টি ও স্মার্ট কৃষি সমাধান দিয়ে কৃষকদের ক্ষমতায়ন।', quickLinks: 'দ্রুত লিঙ্ক', features: 'বৈশিষ্ট্য', rights: 'সর্বস্বত্ব সংরক্ষিত।' },
};
export default bn;
