import type { TranslationKeys } from './en';
const es: TranslationKeys = {
  nav: { home: 'Inicio', seedGuide: 'Guía de Semillas', weather: 'Clima', aiTools: 'Herramientas AI', farmManagement: 'Gestión de Granja', community: 'Comunidad', sos: 'SOS', contact: 'Contacto', login: 'Iniciar Sesión', signup: 'Registrarse', logout: 'Cerrar Sesión', aiDecisionEngine: '🧠 Motor de Decisión AI', voiceAssistant: '🎙️ Asistente de Voz', profitPrediction: '📈 Predicción de Ganancias', diseaseScanner: '🔬 Escáner de Enfermedades', expenseTracker: '💰 Rastreador de Gastos', iotMonitoring: '📡 Monitoreo IoT', digitalTwin: '🗺️ Gemelo Digital', farmerCommunity: '💬 Comunidad Agrícola', marketplace: '🛒 Mercado', govtSchemes: '🏛️ Programas Gubernamentales', learningHub: '📚 Centro de Aprendizaje', emergencySOS: '🚨 SOS de Emergencia', switchTheme: 'Cambiar Tema' },
  hero: { badge: 'Plataforma Agrícola Inteligente', title1: 'Cultiva con Inteligencia,', title2: 'Cosecha Mejor', description: 'AgriAssist trae tecnología de vanguardia a tus campos. Optimiza tu granja con recomendaciones impulsadas por IA.', getStarted: 'Comenzar', exploreFeatures: 'Explorar Funciones', yieldIncrease: 'Aumento de Rendimiento', costReduction: 'Reducción de Costos', monitoring: 'Monitoreo' },
  features: { badge: 'Funciones Poderosas', title: 'Todo lo que Necesitas para Cultivar con Inteligencia', subtitle: 'Nuestra plataforma combina IA, IoT y análisis de datos para ayudarte a tomar mejores decisiones agrícolas.' },
  cta: { title: '¿Listo para Transformar tu Agricultura?', subtitle: 'Únete a miles de agricultores que ya usan AgriAssist para aumentar rendimientos y reducir costos.', startTrial: 'Iniciar Prueba Gratuita', scheduleDemo: 'Programar Demo' },
  weather: { title: 'Pronóstico Meteorológico Agrícola', subtitle: 'Datos meteorológicos en tiempo real con información específica para la agricultura', searchPlaceholder: 'Buscar ciudad o ubicación...', current: 'Actual', forecast: 'Pronóstico', calendar: 'Calendario', humidity: 'Humedad', wind: 'Viento', pressure: 'Presión', visibility: 'Visibilidad', sunrise: 'Amanecer', sunset: 'Atardecer', feelsLike: 'Sensación', uvIndex: 'Índice UV', dewPoint: 'Punto de Rocío', rainfall: 'Lluvia', farmingAdvisory: 'Asesoría Agrícola de Hoy', noAlerts: 'Sin Alertas Activas', weatherAlert: 'Alerta Meteorológica', forecastTitle: 'Pronóstico de 14 Días', goodFarmDays: 'Buenos Días para Cultivar', rainyDays: 'Días Lluviosos', avgTemp: 'Temperatura Promedio', avgHumidity: 'Humedad Promedio' },
  marketplace: { badge: 'Mercado Agrícola', title: 'Mercado de Granja y Compartición de Recursos', subtitle: 'Compra/vende semillas, herramientas, equipos. Alquila tractores, contrata mano de obra.', searchPlaceholder: 'Buscar semillas, herramientas, tractores, mano de obra...', allCategories: 'Todas las Categorías', seeds: 'Semillas', tools: 'Herramientas', equipment: 'Equipos', labor: 'Mano de Obra', tractorRental: 'Alquiler de Tractor', postListing: 'Publicar Anuncio', chatWhatsApp: 'Chatear en WhatsApp', contactSeller: 'Contactar Vendedor', soldOut: 'Agotado', whatsappAvailable: 'WhatsApp disponible', postNewListing: 'Publicar Nuevo Anuncio', productName: 'Nombre del Producto / Servicio', category: 'Categoría', price: 'Precio', unit: 'Unidad / Período', sellerName: 'Tu Nombre / Nombre de Tienda', location: 'Ubicación', whatsappNumber: 'Número de WhatsApp', description: 'Descripción', productImage: 'Imagen del Producto', cancel: 'Cancelar', postWithWhatsApp: 'Publicar con WhatsApp', listingPosted: '¡Anuncio Publicado!', noListings: 'No se encontraron anuncios. Prueba una búsqueda o categoría diferente.' },
  seedGuide: { badge: 'Guía de Semillas', title: 'Encuentra las Semillas Perfectas para tu Granja', subtitle: 'Explora nuestra colección de semillas optimizadas para diferentes regiones, suelos y climas.', recommendations: 'Recomendaciones', calculator: 'Calculadora de Semillas', catalog: 'Catálogo Completo', searchPlaceholder: 'Buscar semillas...', season: 'Temporada', allSeasons: 'Todas las Temporadas', clearFilters: 'Limpiar filtros', noSeeds: 'No se encontraron semillas que coincidan con tus criterios.', fullCatalog: '🌱 Catálogo Completo – Guía de Semillas', catalogSubtitle: 'Colección completa de semillas para todas tus necesidades agrícolas', vegetables: '1. Verduras', fruits: '2. Frutas', flowers: '3. Flores', fieldCrops: '4. Cultivos de Campo', growthDuration: 'Duración de Crecimiento', climateSoil: 'Clima/Suelo', yieldPotential: 'Potencial de Rendimiento', careTips: 'Consejos de Cuidado' },
  ai: { badge: 'Inteligencia Impulsada por AI', title: 'Motor de Decisión de Granja AI', subtitle: 'Completa los detalles de tu granja y obtén un informe completo.', farmConditions: 'Condiciones de la Granja', cropType: 'Tipo de Cultivo', soilType: 'Tipo de Suelo', cropStage: 'Etapa del Cultivo', season: 'Temporada', irrigationSource: 'Fuente de Irrigación', stateRegion: 'Estado / Región', farmArea: 'Área de la Granja (acres)', temperature: 'Temperatura', soilMoisture: 'Humedad del Suelo', generateReport: 'Generar Informe Completo de Granja', readyToAnalyze: 'Listo para Analizar', readySubtitle: 'Completa las condiciones de tu granja para obtener información impulsada por AI.', cropOverview: 'Resumen del Cultivo y Datos Clave', irrigationPlan: 'Plan de Irrigación', fertilizerSchedule: 'Programa de Fertilización', pestRisk: 'Evaluación de Riesgo de Plagas y Enfermedades', weeklyPlan: 'Plan de Acción de 7 Días', profitEstimate: 'Estimación de Ganancias e Ingresos', govtSchemes: 'Programas Gubernamentales Relevantes', aiGenerated: 'Generado por AI', missingFields: 'Campos faltantes', missingFieldsDesc: 'Por favor completa Cultivo, Suelo, Etapa y Temporada.', reportReady: 'Informe de Granja Listo' },
  common: { loading: 'Cargando...', search: 'Buscar', filter: 'Filtrar', submit: 'Enviar', cancel: 'Cancelar', save: 'Guardar', delete: 'Eliminar', edit: 'Editar', close: 'Cerrar', back: 'Atrás', next: 'Siguiente', previous: 'Anterior', viewAll: 'Ver Todo', learnMore: 'Saber Más', getStarted: 'Comenzar', required: 'Requerido', optional: 'opcional', yes: 'Sí', no: 'No', high: 'Alto', medium: 'Medio', low: 'Bajo', excellent: 'Excelente', good: 'Bueno', fair: 'Regular', poor: 'Malo' },
  footer: { tagline: 'Empoderando a los agricultores con información impulsada por AI y soluciones agrícolas inteligentes.', quickLinks: 'Enlaces Rápidos', features: 'Funciones', rights: 'Todos los derechos reservados.' },
};
export default es;
