import type { TranslationKeys } from './en';
const gu: TranslationKeys = {
  nav: { home: 'હોમ', seedGuide: 'બીજ માર્ગદર્શિકા', weather: 'હવામાન', aiTools: 'AI સાધનો', farmManagement: 'ખેત વ્યવસ્થાપન', community: 'સમુદાય', sos: 'SOS', contact: 'સંપર્ક', login: 'લૉગિન', signup: 'સાઇન અપ', logout: 'લૉગઆઉટ', aiDecisionEngine: '🧠 AI નિર્ણય એન્જિન', voiceAssistant: '🎙️ વૉઇસ આસિસ્ટન્ટ', profitPrediction: '📈 નફો અનુમાન', diseaseScanner: '🔬 રોગ સ્કેનર', expenseTracker: '💰 ખર્ચ ટ્રૅકર', iotMonitoring: '📡 IoT દેખરેખ', digitalTwin: '🗺️ ડિજિટલ ટ્વિન', farmerCommunity: '💬 ખેડૂત સમુદાય', marketplace: '🛒 બજાર', govtSchemes: '🏛️ સરકારી યોજનાઓ', learningHub: '📚 શિક્ષણ કેન્દ્ર', emergencySOS: '🚨 કટોકટી SOS', switchTheme: 'થીમ બદલો' },
  hero: { badge: 'સ્માર્ટ કૃષિ પ્લેટફોર્મ', title1: 'સ્માર્ટ ખેતી કરો,', title2: 'સારો પાક લો', description: 'AgriAssist તમારા ખેતરોમાં અત્યાધુનિક ટેક્નોલૉજી લાવે છે।', getStarted: 'શરૂ કરો', exploreFeatures: 'સુવિધાઓ જુઓ', yieldIncrease: 'ઉત્પાદન વૃદ્ધિ', costReduction: 'ખર્ચ ઘટાડો', monitoring: 'દેખરેખ' },
  features: { badge: 'શક્તિશાળી સુવિધાઓ', title: 'સ્માર્ટ ખેતી માટે બધું', subtitle: 'અમારું પ્લેટફોર્મ AI, IoT અને ડેટા વિશ્લેષણ જોડે છે।' },
  cta: { title: 'તમારી ખેતી બદલવા તૈયાર છો?', subtitle: 'હજારો ખેડૂતો સાથે જોડાઓ જે AgriAssist વાપરી રહ્યા છે।', startTrial: 'મફત ટ્રાયલ શરૂ કરો', scheduleDemo: 'ડેમો શેડ્યૂલ કરો' },
  weather: { title: 'કૃષિ હવામાન અનુમાન', subtitle: 'ખેતી-વિશિષ્ટ માહિતી સાથે રિઅલ-ટાઇમ હવામાન ડેટા', searchPlaceholder: 'શહેર અથવા સ્થળ શોધો...', current: 'વર્તમાન', forecast: 'અનુમાન', calendar: 'કૅલેન્ડર', humidity: 'ભેજ', wind: 'પવન', pressure: 'દબાણ', visibility: 'દૃશ્યતા', sunrise: 'સૂર્યોદય', sunset: 'સૂર્યાસ્ત', feelsLike: 'અનુભવ', uvIndex: 'UV સૂચકાંક', dewPoint: 'ઝાકળ બિંદુ', rainfall: 'વરસાદ', farmingAdvisory: 'આજની ખેતી સલાહ', noAlerts: 'કોઈ સક્રિય ચેતવણી નથી', weatherAlert: 'હવામાન ચેતવણી', forecastTitle: '૧૪-દિવસનું અનુમાન', goodFarmDays: 'સારા ખેતી દિવસ', rainyDays: 'વરસાદી દિવસ', avgTemp: 'સરેરાશ તાપમાન', avgHumidity: 'સરેરાશ ભેજ' },
  marketplace: { badge: 'ખેડૂત બજાર', title: 'ફાર્મ માર્કેટપ્લેસ અને સ્ત્રોત વહેંચણી', subtitle: 'બીજ, સાધનો, સાધનસામગ્રી ખરીદો/વેચો।', searchPlaceholder: 'બીજ, સાધનો, ટ્રૅક્ટર, મજૂર શોધો...', allCategories: 'બધી શ્રેણીઓ', seeds: 'બીજ', tools: 'સાધનો', equipment: 'સાધનસામગ્રી', labor: 'મજૂર', tractorRental: 'ટ્રૅક્ટર ભાડું', postListing: 'યાદી પોસ્ટ કરો', chatWhatsApp: 'WhatsApp પર ચૅટ કરો', contactSeller: 'વેચનારનો સંપર્ક કરો', soldOut: 'વેચાઈ ગયું', whatsappAvailable: 'WhatsApp ઉપલબ્ધ', postNewListing: 'નવી યાદી પોસ્ટ કરો', productName: 'ઉત્પાદ / સેવાનું નામ', category: 'શ્રેણી', price: 'કિંમત', unit: 'એકમ / સમયગાળો', sellerName: 'તમારું નામ / દુકાનનું નામ', location: 'સ્થળ', whatsappNumber: 'WhatsApp મોબાઇલ નંબર', description: 'વર્ણન', productImage: 'ઉત્પાદ છબી', cancel: 'રદ કરો', postWithWhatsApp: 'WhatsApp સાથે પોસ્ટ કરો', listingPosted: 'યાદી પોસ્ટ થઈ!', noListings: 'કોઈ યાદી મળી નથી।' },
  seedGuide: { badge: 'બીજ માર્ગદર્શિકા', title: 'તમારા ખેતર માટે સાચા બીજ શોધો', subtitle: 'વિવિધ પ્રદેશ, માટી અને આબોહવા માટે ઑપ્ટિમાઇઝ બીજોનો સંગ્રહ જુઓ।', recommendations: 'ભલામણો', calculator: 'બીજ કૅલ્ક્યુલેટર', catalog: 'સંપૂર્ણ કૅટેલૉગ', searchPlaceholder: 'બીજ શોધો...', season: 'ઋતુ', allSeasons: 'બધી ઋતુઓ', clearFilters: 'ફિલ્ટર સાફ કરો', noSeeds: 'તમારા માપદંડ સાથે મેળ ખાતા બીજ મળ્યા નથી।', fullCatalog: '🌱 સંપૂર્ણ કૅટેલૉગ – બીજ માર્ગદર્શિકા', catalogSubtitle: 'તમારી બધી ખેતી જરૂરિયાતો માટે બીજોનો સંપૂર્ણ સંગ્રહ', vegetables: '૧. શાકભાજી', fruits: '૨. ફળ', flowers: '૩. ફૂલ', fieldCrops: '૪. ખેતરના પાક', growthDuration: 'વૃદ્ધિ સમયગાળો', climateSoil: 'આબોહવા/માટી', yieldPotential: 'ઉત્પાદન ક્ષમતા', careTips: 'સંભાળ ટિપ્સ' },
  ai: { badge: 'AI-સંચાલિત બુદ્ધિ', title: 'AI ફાર્મ નિર્ણય એન્જિન', subtitle: 'તમારા ખેતરની વિગત ભરો અને સંપૂર્ણ ફાર્મ રિપોર્ટ મેળવો।', farmConditions: 'ખેતરની સ્થિતિ', cropType: 'પાકનો પ્રકાર', soilType: 'માટીનો પ્રકાર', cropStage: 'પાકની અવસ્થા', season: 'ઋતુ', irrigationSource: 'સિંચાઈ સ્ત્રોત', stateRegion: 'રાજ્ય / પ્રદેશ', farmArea: 'ખેતરનું ક્ષેત્રફળ (એકર)', temperature: 'તાપમાન', soilMoisture: 'માટીની ભેજ', generateReport: 'સંપૂર્ણ ફાર્મ રિપોર્ટ બનાવો', readyToAnalyze: 'વિશ્લેષણ માટે તૈયાર', readySubtitle: 'AI-સંચાલિત માહિતી માટે ખેતરની સ્થિતિ ભરો।', cropOverview: 'પાક સારાંશ અને મુખ્ય તથ્યો', irrigationPlan: 'સિંચાઈ યોજના', fertilizerSchedule: 'ખાતર સમયપત્રક', pestRisk: 'જીવાત અને રોગ જોખમ મૂલ્યાંકન', weeklyPlan: '૭-દિવસની કાર્ય યોજના', profitEstimate: 'નફો અને આવક અંદાજ', govtSchemes: 'સંબંધિત સરકારી યોજનાઓ', aiGenerated: 'AI જનિત', missingFields: 'અધૂરા ક્ષેત્રો', missingFieldsDesc: 'કૃપા કરીને પાક, માટી, અવસ્થા અને ઋતુ ભરો।', reportReady: 'ફાર્મ રિપોર્ટ તૈયાર' },
  common: { loading: 'લોડ થઈ રહ્યું છે...', search: 'શોધો', filter: 'ફિલ્ટર', submit: 'સબમિટ કરો', cancel: 'રદ કરો', save: 'સાચવો', delete: 'કાઢો', edit: 'સંપાદિત કરો', close: 'બંધ કરો', back: 'પાછળ', next: 'આગળ', previous: 'પહેલાં', viewAll: 'બધું જુઓ', learnMore: 'વધુ જાણો', getStarted: 'શરૂ કરો', required: 'જરૂરી', optional: 'વૈકલ્પિક', yes: 'હા', no: 'ના', high: 'ઊંચ', medium: 'મધ્યમ', low: 'ઓછ', excellent: 'ઉત્કૃષ્ટ', good: 'સારું', fair: 'ઠીક', poor: 'ખરાબ' },
  footer: { tagline: 'AI-સંચાલિત માહિતી અને સ્માર્ટ કૃષિ ઉકેલો સાથે ખેડૂતોને સશક્ત બનાવવું।', quickLinks: 'ઝડપી લિંક', features: 'સુવિધાઓ', rights: 'સર્વ હક્ક સુરક્ષિત।' },
};
export default gu;
