
import type { TranslationKeys } from './en';
const hi: TranslationKeys = {
  nav: { home:'होम', seedGuide:'बीज गाइड', weather:'मौसम', aiTools:'AI टूल्स', farmManagement:'खेत प्रबंधन', community:'समुदाय', sos:'SOS', contact:'संपर्क', login:'लॉगिन', signup:'साइन अप', logout:'लॉगआउट', aiDecisionEngine:'🧠 AI निर्णय इंजन', voiceAssistant:'🎙️ वॉयस असिस्टेंट', profitPrediction:'📈 लाभ पूर्वानुमान', diseaseScanner:'🔬 रोग स्कैनर', expenseTracker:'💰 खर्च ट्रैकर', iotMonitoring:'📡 IoT निगरानी', digitalTwin:'🗺️ डिजिटल ट्विन', farmerCommunity:'💬 किसान समुदाय', marketplace:'🛒 बाज़ार', govtSchemes:'🏛️ सरकारी योजनाएं', learningHub:'📚 लर्निंग हब', emergencySOS:'🚨 आपातकालीन SOS', switchTheme:'थीम बदलें' },
  hero: { badge:'स्मार्ट कृषि प्लेटफॉर्म', title1:'स्मार्ट खेती करें,', title2:'बेहतर फसल काटें', description:'AgriAssist आपके खेतों में अत्याधुनिक तकनीक लाता है। AI-संचालित सिफारिशों और रियल-टाइम निगरानी के साथ अपने खेत को अनुकूलित करें।', getStarted:'शुरू करें', exploreFeatures:'सुविधाएं देखें', yieldIncrease:'उपज वृद्धि', costReduction:'लागत में कमी', monitoring:'निगरानी' },
  features: { badge:'स्मार्ट सुविधाएं', title:'स्मार्ट खेती के लिए सब कुछ', subtitle:'AgriAssist अत्याधुनिक तकनीक को कृषि विशेषज्ञता के साथ जोड़ता है।', openFeature:'सुविधा खोलें', exploreAll:'सभी सुविधाएं देखें', items:[{title:'मौसमी बीज गाइड',description:'स्थान, मिट्टी और मौसम के आधार पर AI-संचालित बीज सिफारिशें।',detail:'20+ फसल किस्में ब्राउज़ करें।'},{title:'खर्च और लाभ ट्रैकर',description:'खेत के खर्च और आय ट्रैक करें, रिपोर्ट बनाएं।',detail:'लाइव टोटल: खर्च, आय, शुद्ध लाभ और ROI।'},{title:'AI फसल निर्णय इंजन',description:'मौसम डेटा और मिट्टी की स्थिति से बुद्धिमान सिफारिशें।',detail:'फसल, मिट्टी, अवस्था और मौसम दर्ज करें।'},{title:'IoT खेत निगरानी',description:'रियल-टाइम में मिट्टी की नमी, तापमान और आर्द्रता निगरानी।',detail:'IoT सेंसर कनेक्ट या सिमुलेट करें।'},{title:'मौसम पूर्वानुमान',description:'कृषि योजना के लिए सटीक मौसम डेटा।',detail:'14-दिन का पूर्वानुमान और कृषि कैलेंडर।'},{title:'पौधे रोग स्कैनर',description:'AI से फसल रोगों के शुरुआती संकेत पहचानें।',detail:'फोटो अपलोड करें और रोग पहचानें।'}] },
  additionalFeatures: { badge:'और सुविधाएं', title:'आधुनिक कृषि के लिए उन्नत उपकरण', subtitle:'AgriAssist आपके खेती कार्य के हर पहलू को अनुकूलित करने में मदद करता है।', goToFeature:'सुविधा पर जाएं', featuresCount:'सुविधाएं', languagesCount:'भाषाएं', aiSupport:'AI सहायता', items:[{title:'बाज़ार मूल्य ट्रैकर',description:'विभिन्न बाज़ारों में फसल की कीमतों पर अपडेट रहें।',detail:'लाइव मंडी कीमतें ट्रैक करें।'},{title:'स्वचालित अलर्ट',description:'सिंचाई, उर्वरक और कटाई के लिए समय पर सूचनाएं।',detail:'कस्टम रिमाइंडर सेट करें।'},{title:'कीट और रोग पहचान',description:'AI से फसल रोगों के शुरुआती संकेत पहचानें।',detail:'10+ पौधे रोगों का पता लगाएं।'},{title:'फार्म डिजिटल ट्विन',description:'डिजिटल मानचित्र के रूप में खेत देखें।',detail:'प्रति प्लॉट फसल स्वास्थ्य ट्रैक करें।'},{title:'सामुदायिक फोरम',description:'किसानों से जुड़ें और विशेषज्ञ सलाह पाएं।',detail:'1000+ सक्रिय किसानों के साथ चैट।'}] },
  cta: { title:'अपनी खेती बदलने के लिए तैयार हैं?', subtitle:'हजारों किसानों से जुड़ें जो AgriAssist से उपज बढ़ा रहे हैं।', startTrial:'मुफ्त ट्रायल शुरू करें', scheduleDemo:'डेमो शेड्यूल करें' },
  weather: { title:'कृषि मौसम पूर्वानुमान', subtitle:'कृषि योजना के लिए सटीक मौसम डेटा।', badge:'मौसम बुद्धिमत्ता', searchPlaceholder:'स्थान दर्ज करें...', getWeather:'मौसम देखें', loading:'लोड हो रहा है...', current:'वर्तमान', forecast:'पूर्वानुमान', calendar:'कैलेंडर', humidity:'आर्द्रता', wind:'हवा', pressure:'दबाव', visibility:'दृश्यता', sunrise:'सूर्योदय', sunset:'सूर्यास्त', feelsLike:'महसूस होता है', uvIndex:'UV सूचकांक', dewPoint:'ओस बिंदु', rainfall:'वर्षा', farmingAdvisory:'आज की खेती सलाह', noAlerts:'कोई अलर्ट नहीं', weatherAlert:'मौसम अलर्ट', forecastTitle:'14-दिन का पूर्वानुमान', goodFarmDays:'अच्छे खेती दिन', rainyDays:'बारिश के दिन', avgTemp:'औसत तापमान', avgHumidity:'औसत आर्द्रता', locationNotFound:'स्थान नहीं मिला', weatherUpdated:'मौसम अपडेट हुआ', showingWeatherFor:'मौसम दिखाया जा रहा है' },
  marketplace: { badge:'किसान बाज़ार', title:'फार्म मार्केटप्लेस', subtitle:'बीज, उपकरण खरीदें/बेचें। ट्रैक्टर किराए पर लें।', searchPlaceholder:'बीज, उपकरण खोजें...', allCategories:'सभी श्रेणियां', seeds:'बीज', tools:'उपकरण', equipment:'यंत्र', labor:'मजदूर', tractorRental:'ट्रैक्टर किराया', postListing:'लिस्टिंग पोस्ट करें', chatWhatsApp:'WhatsApp पर चैट करें', contactSeller:'विक्रेता से संपर्क करें', soldOut:'बिक गया', whatsappAvailable:'WhatsApp उपलब्ध', postNewListing:'नई लिस्टिंग पोस्ट करें', productName:'उत्पाद का नाम', category:'श्रेणी', price:'मूल्य', unit:'इकाई', sellerName:'आपका नाम', location:'स्थान', whatsappNumber:'WhatsApp नंबर', description:'विवरण', productImage:'उत्पाद छवि', cancel:'रद्द करें', postWithWhatsApp:'WhatsApp के साथ पोस्ट करें', listingPosted:'लिस्टिंग पोस्ट हो गई!', noListings:'कोई लिस्टिंग नहीं मिली।' },
  seedGuide: { badge:'बीज गाइड', title:'अपने खेत के लिए सही बीज खोजें', subtitle:'विभिन्न क्षेत्रों और जलवायु के लिए बीजों का संग्रह देखें।', recommendations:'सिफारिशें', calculator:'बीज कैलकुलेटर', catalog:'पूर्ण कैटलॉग', searchPlaceholder:'बीज खोजें...', season:'मौसम', allSeasons:'सभी मौसम', clearFilters:'फ़िल्टर साफ़ करें', noSeeds:'कोई बीज नहीं मिला।', fullCatalog:'🌱 पूर्ण कैटलॉग', catalogSubtitle:'सभी खेती जरूरतों के लिए बीजों का संग्रह', vegetables:'1. सब्जियां', fruits:'2. फल', flowers:'3. फूल', fieldCrops:'4. खेत की फसलें', growthDuration:'विकास अवधि', climateSoil:'जलवायु/मिट्टी', yieldPotential:'उपज क्षमता', careTips:'देखभाल टिप्स' },
  ai: { badge:'AI-संचालित बुद्धिमत्ता', title:'AI फार्म निर्णय इंजन', subtitle:'खेत का विवरण भरें और पूरी फार्म रिपोर्ट प्राप्त करें।', farmConditions:'खेत की स्थिति', cropType:'फसल का प्रकार', soilType:'मिट्टी का प्रकार', cropStage:'फसल अवस्था', season:'मौसम', irrigationSource:'सिंचाई स्रोत', stateRegion:'राज्य / क्षेत्र', farmArea:'खेत का क्षेत्रफल (एकड़)', temperature:'तापमान', soilMoisture:'मिट्टी की नमी', generateReport:'पूरी फार्म रिपोर्ट बनाएं', readyToAnalyze:'विश्लेषण के लिए तैयार', readySubtitle:'AI अंतर्दृष्टि के लिए खेत की स्थिति भरें।', cropOverview:'फसल अवलोकन', irrigationPlan:'सिंचाई योजना', fertilizerSchedule:'उर्वरक अनुसूची', pestRisk:'कीट और रोग जोखिम', weeklyPlan:'7-दिन की कार्य योजना', profitEstimate:'लाभ अनुमान', govtSchemes:'सरकारी योजनाएं', aiGenerated:'AI जनित', missingFields:'अधूरे फ़ील्ड', missingFieldsDesc:'कृपया फसल, मिट्टी, अवस्था और मौसम भरें।', reportReady:'फार्म रिपोर्ट तैयार' },
  contact: { title:'संपर्क करें', subtitle:'अपने खेत प्रबंधन के लिए हमारे विशेषज्ञों से संपर्क करें', reportIssue:'कृषि समस्या रिपोर्ट करें', fullName:'पूरा नाम', fullNamePlaceholder:'अपना पूरा नाम दर्ज करें', address:'पता', addressPlaceholder:'अपना गांव या खेत का स्थान दर्ज करें', phone:'फोन नंबर', phonePlaceholder:'अपना फोन नंबर दर्ज करें', email:'ईमेल पता', emailPlaceholder:'अपना ईमेल पता दर्ज करें', subject:'विषय', subjectPlaceholder:'उदाहरण: मक्के के बीज की समस्या', problemDesc:'समस्या का विवरण', problemPlaceholder:'अपनी फसल की समस्या का विस्तार से वर्णन करें...', problemNote:'नोट: फसल का प्रकार और लक्षण शामिल करें।', submitReport:'रिपोर्ट जमा करें', contactInfo:'संपर्क जानकारी', ourLocation:'हमारा स्थान', phoneNumbers:'फोन नंबर', emailLabel:'ईमेल', emergencyNumbers:'राष्ट्रीय आपातकालीन नंबर' },
  footer: { tagline:'बेहतर उपज के लिए स्मार्ट कृषि समाधानों के साथ किसानों को सशक्त बनाना।', quickLinks:'त्वरित लिंक', resources:'संसाधन', contactUs:'संपर्क करें', home:'होम', seedGuide:'बीज गाइड', expenseTracker:'खर्च ट्रैकर', weatherForecast:'मौसम पूर्वानुमान', iotMonitoring:'IoT निगरानी', cropGuidelines:'फसल दिशानिर्देश', pestControl:'कीट नियंत्रण', marketTrends:'बाज़ार रुझान', expertAdvice:'विशेषज्ञ सलाह', communityForum:'सामुदायिक फोरम', rights:'सर्वाधिकार सुरक्षित।' },
  govtSchemes: { badge:'सरकारी योजनाएं', title:'सरकारी योजना अनुशंसाकर्ता', subtitle:'अपने खेत प्रोफाइल के अनुसार सब्सिडी और योजनाएं खोजें।', apply:'आवेदन करें', noSchemes:'कोई योजना नहीं मिली।' },
  community: { title:'किसान समुदाय', subtitle:'किसानों से जुड़ें और एक साथ बढ़ें।' },
  common: { loading:'लोड हो रहा है...', search:'खोजें', filter:'फ़िल्टर', submit:'जमा करें', cancel:'रद्द करें', save:'सहेजें', delete:'हटाएं', edit:'संपादित करें', close:'बंद करें', back:'वापस', next:'अगला', previous:'पिछला', viewAll:'सभी देखें', learnMore:'और जानें', getStarted:'शुरू करें', required:'आवश्यक', optional:'वैकल्पिक', yes:'हां', no:'नहीं', high:'उच्च', medium:'मध्यम', low:'कम', excellent:'उत्कृष्ट', good:'अच्छा', fair:'ठीक', poor:'खराब' },
};
export default hi;
