import type { TranslationKeys } from './en';
const kn: TranslationKeys = {
  nav: { home: 'ಮುಖಪುಟ', seedGuide: 'ಬೀಜ ಮಾರ್ಗದರ್ಶಿ', weather: 'ಹವಾಮಾನ', aiTools: 'AI ಸಾಧನಗಳು', farmManagement: 'ಕೃಷಿ ನಿರ್ವಹಣೆ', community: 'ಸಮುದಾಯ', sos: 'SOS', contact: 'ಸಂಪರ್ಕ', login: 'ಲಾಗಿನ್', signup: 'ಸೈನ್ ಅಪ್', logout: 'ಲಾಗ್‌ಔಟ್', aiDecisionEngine: '🧠 AI ನಿರ್ಧಾರ ಎಂಜಿನ್', voiceAssistant: '🎙️ ವಾಯ್ಸ್ ಅಸಿಸ್ಟೆಂಟ್', profitPrediction: '📈 ಲಾಭ ಮುನ್ಸೂಚನೆ', diseaseScanner: '🔬 ರೋಗ ಸ್ಕ್ಯಾನರ್', expenseTracker: '💰 ವೆಚ್ಚ ಟ್ರ್ಯಾಕರ್', iotMonitoring: '📡 IoT ಮೇಲ್ವಿಚಾರಣೆ', digitalTwin: '🗺️ ಡಿಜಿಟಲ್ ಟ್ವಿನ್', farmerCommunity: '💬 ರೈತ ಸಮುದಾಯ', marketplace: '🛒 ಮಾರುಕಟ್ಟೆ', govtSchemes: '🏛️ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು', learningHub: '📚 ಕಲಿಕಾ ಕೇಂದ್ರ', emergencySOS: '🚨 ತುರ್ತು SOS', switchTheme: 'ಥೀಮ್ ಬದಲಿಸಿ' },
  hero: { badge: 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ವೇದಿಕೆ', title1: 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಮಾಡಿ,', title2: 'ಉತ್ತಮ ಬೆಳೆ ತೆಗೆಯಿರಿ', description: 'AgriAssist ನಿಮ್ಮ ಹೊಲಗಳಿಗೆ ಅತ್ಯಾಧುನಿಕ ತಂತ್ರಜ್ಞಾನ ತರುತ್ತದೆ।', getStarted: 'ಪ್ರಾರಂಭಿಸಿ', exploreFeatures: 'ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಅನ್ವೇಷಿಸಿ', yieldIncrease: 'ಇಳುವರಿ ಹೆಚ್ಚಳ', costReduction: 'ವೆಚ್ಚ ಕಡಿತ', monitoring: 'ಮೇಲ್ವಿಚಾರಣೆ' },
  features: { badge: 'ಶಕ್ತಿಶಾಲಿ ವೈಶಿಷ್ಟ್ಯಗಳು', title: 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿಗೆ ಅಗತ್ಯವಿರುವ ಎಲ್ಲವೂ', subtitle: 'ನಮ್ಮ ವೇದಿಕೆ AI, IoT ಮತ್ತು ಡೇಟಾ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಸಂಯೋಜಿಸುತ್ತದೆ।' },
  cta: { title: 'ನಿಮ್ಮ ಕೃಷಿಯನ್ನು ಬದಲಾಯಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?', subtitle: 'AgriAssist ಬಳಸುತ್ತಿರುವ ಸಾವಿರಾರು ರೈತರೊಂದಿಗೆ ಸೇರಿ।', startTrial: 'ಉಚಿತ ಟ್ರಯಲ್ ಪ್ರಾರಂಭಿಸಿ', scheduleDemo: 'ಡೆಮೋ ನಿಗದಿಪಡಿಸಿ' },
  weather: { title: 'ಕೃಷಿ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ', subtitle: 'ಕೃಷಿ-ನಿರ್ದಿಷ್ಟ ಒಳನೋಟದೊಂದಿಗೆ ರಿಯಲ್-ಟೈಮ್ ಹವಾಮಾನ ಡೇಟಾ', searchPlaceholder: 'ನಗರ ಅಥವಾ ಸ್ಥಳ ಹುಡುಕಿ...', current: 'ಪ್ರಸ್ತುತ', forecast: 'ಮುನ್ಸೂಚನೆ', calendar: 'ಕ್ಯಾಲೆಂಡರ್', humidity: 'ತೇವಾಂಶ', wind: 'ಗಾಳಿ', pressure: 'ಒತ್ತಡ', visibility: 'ಗೋಚರತೆ', sunrise: 'ಸೂರ್ಯೋದಯ', sunset: 'ಸೂರ್ಯಾಸ್ತ', feelsLike: 'ಅನಿಸುತ್ತದೆ', uvIndex: 'UV ಸೂಚ್ಯಂಕ', dewPoint: 'ಇಬ್ಬನಿ ಬಿಂದು', rainfall: 'ಮಳೆ', farmingAdvisory: 'ಇಂದಿನ ಕೃಷಿ ಸಲಹೆ', noAlerts: 'ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ', weatherAlert: 'ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ', forecastTitle: '14-ದಿನಗಳ ಮುನ್ಸೂಚನೆ', goodFarmDays: 'ಉತ್ತಮ ಕೃಷಿ ದಿನಗಳು', rainyDays: 'ಮಳೆ ದಿನಗಳು', avgTemp: 'ಸರಾಸರಿ ತಾಪಮಾನ', avgHumidity: 'ಸರಾಸರಿ ತೇವಾಂಶ' },
  marketplace: { badge: 'ರೈತ ಮಾರುಕಟ್ಟೆ', title: 'ಫಾರ್ಮ್ ಮಾರ್ಕೆಟ್‌ಪ್ಲೇಸ್ ಮತ್ತು ಸಂಪನ್ಮೂಲ ಹಂಚಿಕೆ', subtitle: 'ಬೀಜಗಳು, ಉಪಕರಣಗಳು, ಯಂತ್ರಗಳನ್ನು ಖರೀದಿಸಿ/ಮಾರಿ।', searchPlaceholder: 'ಬೀಜಗಳು, ಉಪಕರಣಗಳು, ಟ್ರ್ಯಾಕ್ಟರ್, ಕಾರ್ಮಿಕರು ಹುಡುಕಿ...', allCategories: 'ಎಲ್ಲಾ ವರ್ಗಗಳು', seeds: 'ಬೀಜಗಳು', tools: 'ಉಪಕರಣಗಳು', equipment: 'ಯಂತ್ರಗಳು', labor: 'ಕಾರ್ಮಿಕರು', tractorRental: 'ಟ್ರ್ಯಾಕ್ಟರ್ ಬಾಡಿಗೆ', postListing: 'ಪಟ್ಟಿ ಪೋಸ್ಟ್ ಮಾಡಿ', chatWhatsApp: 'WhatsApp ನಲ್ಲಿ ಚಾಟ್ ಮಾಡಿ', contactSeller: 'ಮಾರಾಟಗಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ', soldOut: 'ಮಾರಾಟವಾಯಿತು', whatsappAvailable: 'WhatsApp ಲಭ್ಯವಿದೆ', postNewListing: 'ಹೊಸ ಪಟ್ಟಿ ಪೋಸ್ಟ್ ಮಾಡಿ', productName: 'ಉತ್ಪನ್ನ / ಸೇವೆಯ ಹೆಸರು', category: 'ವರ್ಗ', price: 'ಬೆಲೆ', unit: 'ಘಟಕ / ಅವಧಿ', sellerName: 'ನಿಮ್ಮ ಹೆಸರು / ಅಂಗಡಿ ಹೆಸರು', location: 'ಸ್ಥಳ', whatsappNumber: 'WhatsApp ಮೊಬೈಲ್ ಸಂಖ್ಯೆ', description: 'ವಿವರಣೆ', productImage: 'ಉತ್ಪನ್ನ ಚಿತ್ರ', cancel: 'ರದ್ದು ಮಾಡಿ', postWithWhatsApp: 'WhatsApp ನೊಂದಿಗೆ ಪೋಸ್ಟ್ ಮಾಡಿ', listingPosted: 'ಪಟ್ಟಿ ಪೋಸ್ಟ್ ಆಯಿತು!', noListings: 'ಯಾವುದೇ ಪಟ್ಟಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ।' },
  seedGuide: { badge: 'ಬೀಜ ಮಾರ್ಗದರ್ಶಿ', title: 'ನಿಮ್ಮ ಹೊಲಕ್ಕೆ ಸರಿಯಾದ ಬೀಜಗಳನ್ನು ಹುಡುಕಿ', subtitle: 'ವಿವಿಧ ಪ್ರದೇಶಗಳು, ಮಣ್ಣು ಮತ್ತು ಹವಾಮಾನಕ್ಕೆ ಅನುಕೂಲಿಸಿದ ಬೀಜಗಳ ಸಂಗ್ರಹ ನೋಡಿ।', recommendations: 'ಶಿಫಾರಸುಗಳು', calculator: 'ಬೀಜ ಕ್ಯಾಲ್ಕುಲೇಟರ್', catalog: 'ಸಂಪೂರ್ಣ ಕ್ಯಾಟಲಾಗ್', searchPlaceholder: 'ಬೀಜಗಳನ್ನು ಹುಡುಕಿ...', season: 'ಋತು', allSeasons: 'ಎಲ್ಲಾ ಋತುಗಳು', clearFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ', noSeeds: 'ನಿಮ್ಮ ಮಾನದಂಡಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಬೀಜಗಳು ಕಂಡುಬಂದಿಲ್ಲ।', fullCatalog: '🌱 ಸಂಪೂರ್ಣ ಕ್ಯಾಟಲಾಗ್ – ಬೀಜ ಮಾರ್ಗದರ್ಶಿ', catalogSubtitle: 'ನಿಮ್ಮ ಎಲ್ಲಾ ಕೃಷಿ ಅಗತ್ಯಗಳಿಗೆ ಬೀಜಗಳ ಸಂಪೂರ್ಣ ಸಂಗ್ರಹ', vegetables: '1. ತರಕಾರಿಗಳು', fruits: '2. ಹಣ್ಣುಗಳು', flowers: '3. ಹೂವುಗಳು', fieldCrops: '4. ಹೊಲದ ಬೆಳೆಗಳು', growthDuration: 'ಬೆಳವಣಿಗೆ ಅವಧಿ', climateSoil: 'ಹವಾಮಾನ/ಮಣ್ಣು', yieldPotential: 'ಇಳುವರಿ ಸಾಮರ್ಥ್ಯ', careTips: 'ಆರೈಕೆ ಸಲಹೆಗಳು' },
  ai: { badge: 'AI-ಚಾಲಿತ ಬುದ್ಧಿಮತ್ತೆ', title: 'AI ಫಾರ್ಮ್ ನಿರ್ಧಾರ ಎಂಜಿನ್', subtitle: 'ನಿಮ್ಮ ಹೊಲದ ವಿವರಗಳನ್ನು ತುಂಬಿ ಮತ್ತು ಸಂಪೂರ್ಣ ಫಾರ್ಮ್ ವರದಿ ಪಡೆಯಿರಿ।', farmConditions: 'ಹೊಲದ ಪರಿಸ್ಥಿತಿಗಳು', cropType: 'ಬೆಳೆ ವಿಧ', soilType: 'ಮಣ್ಣಿನ ವಿಧ', cropStage: 'ಬೆಳೆ ಹಂತ', season: 'ಋತು', irrigationSource: 'ನೀರಾವರಿ ಮೂಲ', stateRegion: 'ರಾಜ್ಯ / ಪ್ರದೇಶ', farmArea: 'ಹೊಲದ ವಿಸ್ತೀರ್ಣ (ಎಕರೆ)', temperature: 'ತಾಪಮಾನ', soilMoisture: 'ಮಣ್ಣಿನ ತೇವಾಂಶ', generateReport: 'ಸಂಪೂರ್ಣ ಫಾರ್ಮ್ ವರದಿ ರಚಿಸಿ', readyToAnalyze: 'ವಿಶ್ಲೇಷಣೆಗೆ ಸಿದ್ಧ', readySubtitle: 'AI-ಚಾಲಿತ ಒಳನೋಟಕ್ಕಾಗಿ ಹೊಲದ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ತುಂಬಿ।', cropOverview: 'ಬೆಳೆ ಅವಲೋಕನ ಮತ್ತು ಪ್ರಮುಖ ಸಂಗತಿಗಳು', irrigationPlan: 'ನೀರಾವರಿ ಯೋಜನೆ', fertilizerSchedule: 'ಗೊಬ್ಬರ ವೇಳಾಪಟ್ಟಿ', pestRisk: 'ಕೀಟ ಮತ್ತು ರೋಗ ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ', weeklyPlan: '7-ದಿನಗಳ ಕ್ರಿಯಾ ಯೋಜನೆ', profitEstimate: 'ಲಾಭ ಮತ್ತು ಆದಾಯ ಅಂದಾಜು', govtSchemes: 'ಸಂಬಂಧಿತ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು', aiGenerated: 'AI ರಚಿಸಿದೆ', missingFields: 'ಅಪೂರ್ಣ ಕ್ಷೇತ್ರಗಳು', missingFieldsDesc: 'ದಯವಿಟ್ಟು ಬೆಳೆ, ಮಣ್ಣು, ಹಂತ ಮತ್ತು ಋತು ತುಂಬಿ।', reportReady: 'ಫಾರ್ಮ್ ವರದಿ ಸಿದ್ಧ' },
  common: { loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', search: 'ಹುಡುಕಿ', filter: 'ಫಿಲ್ಟರ್', submit: 'ಸಲ್ಲಿಸಿ', cancel: 'ರದ್ದು ಮಾಡಿ', save: 'ಉಳಿಸಿ', delete: 'ಅಳಿಸಿ', edit: 'ಸಂಪಾದಿಸಿ', close: 'ಮುಚ್ಚಿ', back: 'ಹಿಂದೆ', next: 'ಮುಂದೆ', previous: 'ಹಿಂದಿನ', viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ', learnMore: 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ', getStarted: 'ಪ್ರಾರಂಭಿಸಿ', required: 'ಅಗತ್ಯ', optional: 'ಐಚ್ಛಿಕ', yes: 'ಹೌದು', no: 'ಇಲ್ಲ', high: 'ಹೆಚ್ಚು', medium: 'ಮಧ್ಯಮ', low: 'ಕಡಿಮೆ', excellent: 'ಅತ್ಯುತ್ತಮ', good: 'ಉತ್ತಮ', fair: 'ಸರಿಯಾದ', poor: 'ಕಳಪೆ' },
  footer: { tagline: 'AI-ಚಾಲಿತ ಒಳನೋಟ ಮತ್ತು ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಪರಿಹಾರಗಳೊಂದಿಗೆ ರೈತರನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು।', quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು', features: 'ವೈಶಿಷ್ಟ್ಯಗಳು', rights: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ।' },
};
export default kn;
