import type { TranslationKeys } from './en';
const ml: TranslationKeys = {
  nav: { home: 'ഹോം', seedGuide: 'വിത്ത് ഗൈഡ്', weather: 'കാലാവസ്ഥ', aiTools: 'AI ടൂളുകൾ', farmManagement: 'കൃഷി മാനേജ്മെന്റ്', community: 'കമ്മ്യൂണിറ്റി', sos: 'SOS', contact: 'ബന്ധപ്പെടുക', login: 'ലോഗിൻ', signup: 'സൈൻ അപ്പ്', logout: 'ലോഗ്ഔട്ട്', aiDecisionEngine: '🧠 AI തീരുമാന എഞ്ചിൻ', voiceAssistant: '🎙️ വോയ്സ് അസിസ്റ്റന്റ്', profitPrediction: '📈 ലാഭ പ്രവചനം', diseaseScanner: '🔬 രോഗ സ്കാനർ', expenseTracker: '💰 ചെലവ് ട്രാക്കർ', iotMonitoring: '📡 IoT നിരീക്ഷണം', digitalTwin: '🗺️ ഡിജിറ്റൽ ട്വിൻ', farmerCommunity: '💬 കർഷക കമ്മ്യൂണിറ്റി', marketplace: '🛒 മാർക്കറ്റ്', govtSchemes: '🏛️ സർക്കാർ പദ്ധതികൾ', learningHub: '📚 പഠന കേന്ദ്രം', emergencySOS: '🚨 അടിയന്തര SOS', switchTheme: 'തീം മാറ്റുക' },
  hero: { badge: 'സ്മാർട്ട് കൃഷി പ്ലാറ്റ്ഫോം', title1: 'സ്മാർട്ടായി കൃഷി ചെയ്യൂ,', title2: 'മികച്ച വിളവ് കൊയ്യൂ', description: 'AgriAssist നിങ്ങളുടെ വയലുകളിലേക്ക് അത്യാധുനിക സാങ്കേതികവിദ്യ കൊണ്ടുവരുന്നു।', getStarted: 'ആരംഭിക്കൂ', exploreFeatures: 'സവിശേഷതകൾ കാണൂ', yieldIncrease: 'വിളവ് വർദ്ധന', costReduction: 'ചെലവ് കുറയ്ക്കൽ', monitoring: 'നിരീക്ഷണം' },
  features: { badge: 'ശക്തമായ സവിശേഷതകൾ', title: 'സ്മാർട്ട് കൃഷിക്ക് ആവശ്യമായ എല്ലാം', subtitle: 'ഞങ്ങളുടെ പ്ലാറ്റ്ഫോം AI, IoT, ഡേറ്റ വിശകലനം എന്നിവ സംയോജിപ്പിക്കുന്നു।' },
  cta: { title: 'നിങ്ങളുടെ കൃഷി മാറ്റാൻ തയ്യാറാണോ?', subtitle: 'AgriAssist ഉപയോഗിക്കുന്ന ആയിരക്കണക്കിന് കർഷകരോടൊപ്പം ചേരൂ।', startTrial: 'സൗജന്യ ട്രയൽ ആരംഭിക്കൂ', scheduleDemo: 'ഡെമോ ഷെഡ്യൂൾ ചെയ്യൂ' },
  weather: { title: 'കൃഷി കാലാവസ്ഥ പ്രവചനം', subtitle: 'കൃഷി-നിർദ്ദിഷ്ട ഉൾക്കാഴ്ചയോടെ റിയൽ-ടൈം കാലാവസ്ഥ ഡേറ്റ', searchPlaceholder: 'നഗരം അല്ലെങ്കിൽ സ്ഥലം തിരയൂ...', current: 'നിലവിലെ', forecast: 'പ്രവചനം', calendar: 'കലണ്ടർ', humidity: 'ആർദ്രത', wind: 'കാറ്റ്', pressure: 'മർദ്ദം', visibility: 'ദൃശ്യത', sunrise: 'സൂര്യോദയം', sunset: 'സൂര്യാസ്തമനം', feelsLike: 'അനുഭവപ്പെടുന്നു', uvIndex: 'UV സൂചിക', dewPoint: 'മഞ്ഞ് ബിന്ദു', rainfall: 'മഴ', farmingAdvisory: 'ഇന്നത്തെ കൃഷി ഉപദേശം', noAlerts: 'സജീവ മുന്നറിയിപ്പുകൾ ഇല്ല', weatherAlert: 'കാലാവസ്ഥ മുന്നറിയിപ്പ്', forecastTitle: '14-ദിവസ പ്രവചനം', goodFarmDays: 'നല്ല കൃഷി ദിവസങ്ങൾ', rainyDays: 'മഴ ദിവസങ്ങൾ', avgTemp: 'ശരാശരി താപനില', avgHumidity: 'ശരാശരി ആർദ്രത' },
  marketplace: { badge: 'കർഷക മാർക്കറ്റ്', title: 'ഫാം മാർക്കറ്റ്പ്ലേസ് & റിസോഴ്സ് ഷെയറിംഗ്', subtitle: 'വിത്തുകൾ, ഉപകരണങ്ങൾ, യന്ത്രങ്ങൾ വാങ്ങൂ/വിൽക്കൂ।', searchPlaceholder: 'വിത്തുകൾ, ഉപകരണങ്ങൾ, ട്രാക്ടർ, തൊഴിലാളികൾ തിരയൂ...', allCategories: 'എല്ലാ വിഭാഗങ്ങളും', seeds: 'വിത്തുകൾ', tools: 'ഉപകരണങ്ങൾ', equipment: 'യന്ത്രങ്ങൾ', labor: 'തൊഴിലാളികൾ', tractorRental: 'ട്രാക്ടർ വാടക', postListing: 'ലിസ്റ്റിംഗ് പോസ്റ്റ് ചെയ്യൂ', chatWhatsApp: 'WhatsApp-ൽ ചാറ്റ് ചെയ്യൂ', contactSeller: 'വിൽപ്പനക്കാരനെ ബന്ധപ്പെടൂ', soldOut: 'വിറ്റുതീർന്നു', whatsappAvailable: 'WhatsApp ലഭ്യം', postNewListing: 'പുതിയ ലിസ്റ്റിംഗ് പോസ്റ്റ് ചെയ്യൂ', productName: 'ഉൽപ്പന്നം / സേവനത്തിന്റെ പേര്', category: 'വിഭാഗം', price: 'വില', unit: 'യൂണിറ്റ് / കാലയളവ്', sellerName: 'നിങ്ങളുടെ പേര് / കടയുടെ പേര്', location: 'സ്ഥലം', whatsappNumber: 'WhatsApp മൊബൈൽ നമ്പർ', description: 'വിവരണം', productImage: 'ഉൽപ്പന്ന ചിത്രം', cancel: 'റദ്ദാക്കൂ', postWithWhatsApp: 'WhatsApp-ൽ പോസ്റ്റ് ചെയ്യൂ', listingPosted: 'ലിസ്റ്റിംഗ് പോസ്റ്റ് ചെയ്തു!', noListings: 'ലിസ്റ്റിംഗുകൾ ഒന്നും കണ്ടെത്തിയില്ല।' },
  seedGuide: { badge: 'വിത്ത് ഗൈഡ്', title: 'നിങ്ങളുടെ ഫാമിന് അനുയോജ്യമായ വിത്തുകൾ കണ്ടെത്തൂ', subtitle: 'വിവിധ പ്രദേശങ്ങൾ, മണ്ണ്, കാലാവസ്ഥ എന്നിവയ്ക്ക് അനുകൂലിപ്പിച്ച വിത്തുകളുടെ ശേഖരം കാണൂ।', recommendations: 'ശുപാർശകൾ', calculator: 'വിത്ത് കാൽക്കുലേറ്റർ', catalog: 'പൂർണ്ണ കാറ്റലോഗ്', searchPlaceholder: 'വിത്തുകൾ തിരയൂ...', season: 'സീസൺ', allSeasons: 'എല്ലാ സീസണുകളും', clearFilters: 'ഫിൽട്ടറുകൾ മായ്ക്കൂ', noSeeds: 'നിങ്ങളുടെ മാനദണ്ഡങ്ങൾക്ക് അനുയോജ്യമായ വിത്തുകൾ കണ്ടെത്തിയില്ല।', fullCatalog: '🌱 പൂർണ്ണ കാറ്റലോഗ് – വിത്ത് ഗൈഡ്', catalogSubtitle: 'നിങ്ങളുടെ എല്ലാ കൃഷി ആവശ്യങ്ങൾക്കും വിത്തുകളുടെ പൂർണ്ണ ശേഖരം', vegetables: '1. പച്ചക്കറികൾ', fruits: '2. പഴങ്ങൾ', flowers: '3. പൂക്കൾ', fieldCrops: '4. വയൽ വിളകൾ', growthDuration: 'വളർച്ചാ കാലം', climateSoil: 'കാലാവസ്ഥ/മണ്ണ്', yieldPotential: 'വിളവ് ശേഷി', careTips: 'പരിചരണ നുറുങ്ങുകൾ' },
  ai: { badge: 'AI-ഊർജ്ജിത ബുദ്ധി', title: 'AI ഫാം തീരുമാന എഞ്ചിൻ', subtitle: 'നിങ്ങളുടെ ഫാം വിവരങ്ങൾ പൂരിപ്പിക്കൂ, പൂർണ്ണ ഫാം റിപ്പോർട്ട് നേടൂ।', farmConditions: 'ഫാം അവസ്ഥകൾ', cropType: 'വിള തരം', soilType: 'മണ്ണ് തരം', cropStage: 'വിള ഘട്ടം', season: 'സീസൺ', irrigationSource: 'ജലസേചന ഉറവിടം', stateRegion: 'സംസ്ഥാനം / പ്രദേശം', farmArea: 'ഫാം വിസ്തൃതി (ഏക്കർ)', temperature: 'താപനില', soilMoisture: 'മണ്ണ് ഈർപ്പം', generateReport: 'പൂർണ്ണ ഫാം റിപ്പോർട്ട് സൃഷ്ടിക്കൂ', readyToAnalyze: 'വിശകലനത്തിന് തയ്യാർ', readySubtitle: 'AI-ഊർജ്ജിത ഉൾക്കാഴ്ചയ്ക്ക് ഫാം അവസ്ഥകൾ പൂരിപ്പിക്കൂ।', cropOverview: 'വിള അവലോകനം & പ്രധാന വസ്തുതകൾ', irrigationPlan: 'ജലസേചന പദ്ധതി', fertilizerSchedule: 'വളം ഷെഡ്യൂൾ', pestRisk: 'കീടം & രോഗ അപകട മൂല്യനിർണ്ണയം', weeklyPlan: '7-ദിവസ പ്രവർത്തന പദ്ധതി', profitEstimate: 'ലാഭം & വരുമാന കണക്ക്', govtSchemes: 'ബന്ധപ്പെട്ട സർക്കാർ പദ്ധതികൾ', aiGenerated: 'AI സൃഷ്ടിച്ചത്', missingFields: 'അപൂർണ്ണ ഫീൽഡുകൾ', missingFieldsDesc: 'ദയവായി വിള, മണ്ണ്, ഘട്ടം, സീസൺ പൂരിപ്പിക്കൂ।', reportReady: 'ഫാം റിപ്പോർട്ട് തയ്യാർ' },
  common: { loading: 'ലോഡ് ചെയ്യുന്നു...', search: 'തിരയൂ', filter: 'ഫിൽട്ടർ', submit: 'സമർപ്പിക്കൂ', cancel: 'റദ്ദാക്കൂ', save: 'സേവ് ചെയ്യൂ', delete: 'ഇല്ലാതാക്കൂ', edit: 'എഡിറ്റ് ചെയ്യൂ', close: 'അടയ്ക്കൂ', back: 'പിന്നോട്ട്', next: 'അടുത്തത്', previous: 'മുൻ', viewAll: 'എല്ലാം കാണൂ', learnMore: 'കൂടുതൽ അറിയൂ', getStarted: 'ആരംഭിക്കൂ', required: 'ആവശ്യം', optional: 'ഐച്ഛികം', yes: 'അതെ', no: 'ഇല്ല', high: 'ഉയർന്ന', medium: 'ഇടത്തരം', low: 'കുറഞ്ഞ', excellent: 'മികച്ച', good: 'നല്ല', fair: 'ശരി', poor: 'മോശം' },
  footer: { tagline: 'AI-ഊർജ്ജിത ഉൾക്കാഴ്ചയും സ്മാർട്ട് കൃഷി പരിഹാരങ്ങളും ഉപയോഗിച്ച് കർഷകരെ ശക്തിപ്പെടുത്തുന്നു।', quickLinks: 'ദ്രുത ലിങ്കുകൾ', features: 'സവിശേഷതകൾ', rights: 'എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം।' },
};
export default ml;
