import type { TranslationKeys } from './en';
const mr: TranslationKeys = {
  nav: { home: 'मुख्यपृष्ठ', seedGuide: 'बियाणे मार्गदर्शक', weather: 'हवामान', aiTools: 'AI साधने', farmManagement: 'शेत व्यवस्थापन', community: 'समुदाय', sos: 'SOS', contact: 'संपर्क', login: 'लॉगिन', signup: 'साइन अप', logout: 'लॉगआउट', aiDecisionEngine: '🧠 AI निर्णय इंजिन', voiceAssistant: '🎙️ व्हॉइस असिस्टंट', profitPrediction: '📈 नफा अंदाज', diseaseScanner: '🔬 रोग स्कॅनर', expenseTracker: '💰 खर्च ट्रॅकर', iotMonitoring: '📡 IoT देखरेख', digitalTwin: '🗺️ डिजिटल ट्विन', farmerCommunity: '💬 शेतकरी समुदाय', marketplace: '🛒 बाजार', govtSchemes: '🏛️ सरकारी योजना', learningHub: '📚 शिक्षण केंद्र', emergencySOS: '🚨 आपत्कालीन SOS', switchTheme: 'थीम बदला' },
  hero: { badge: 'स्मार्ट शेती प्लॅटफॉर्म', title1: 'स्मार्ट शेती करा,', title2: 'चांगले पीक काढा', description: 'AgriAssist तुमच्या शेतात अत्याधुनिक तंत्रज्ञान आणतो।', getStarted: 'सुरू करा', exploreFeatures: 'वैशिष्ट्ये पहा', yieldIncrease: 'उत्पादन वाढ', costReduction: 'खर्च कपात', monitoring: 'देखरेख' },
  features: { badge: 'शक्तिशाली वैशिष्ट्ये', title: 'स्मार्ट शेतीसाठी सर्व काही', subtitle: 'आमचे प्लॅटफॉर्म AI, IoT आणि डेटा विश्लेषण एकत्र करते।' },
  cta: { title: 'तुमची शेती बदलण्यास तयार आहात?', subtitle: 'हजारो शेतकऱ्यांसोबत सामील व्हा जे AgriAssist वापरत आहेत।', startTrial: 'मोफत ट्रायल सुरू करा', scheduleDemo: 'डेमो शेड्यूल करा' },
  weather: { title: 'कृषी हवामान अंदाज', subtitle: 'शेती-विशिष्ट माहितीसह रिअल-टाइम हवामान डेटा', searchPlaceholder: 'शहर किंवा ठिकाण शोधा...', current: 'सध्याचे', forecast: 'अंदाज', calendar: 'दिनदर्शिका', humidity: 'आर्द्रता', wind: 'वारा', pressure: 'दाब', visibility: 'दृश्यमानता', sunrise: 'सूर्योदय', sunset: 'सूर्यास्त', feelsLike: 'जाणवते', uvIndex: 'UV निर्देशांक', dewPoint: 'दव बिंदू', rainfall: 'पाऊस', farmingAdvisory: 'आजचा शेती सल्ला', noAlerts: 'कोणतेही सक्रिय अलर्ट नाही', weatherAlert: 'हवामान अलर्ट', forecastTitle: '१४-दिवसांचा अंदाज', goodFarmDays: 'चांगले शेती दिवस', rainyDays: 'पावसाचे दिवस', avgTemp: 'सरासरी तापमान', avgHumidity: 'सरासरी आर्द्रता' },
  marketplace: { badge: 'शेतकरी बाजार', title: 'फार्म मार्केटप्लेस आणि संसाधन सामायिकरण', subtitle: 'बियाणे, साधने, उपकरणे खरेदी/विक्री करा।', searchPlaceholder: 'बियाणे, साधने, ट्रॅक्टर, मजूर शोधा...', allCategories: 'सर्व श्रेणी', seeds: 'बियाणे', tools: 'साधने', equipment: 'उपकरणे', labor: 'मजूर', tractorRental: 'ट्रॅक्टर भाडे', postListing: 'यादी पोस्ट करा', chatWhatsApp: 'WhatsApp वर चॅट करा', contactSeller: 'विक्रेत्याशी संपर्क करा', soldOut: 'विकले गेले', whatsappAvailable: 'WhatsApp उपलब्ध', postNewListing: 'नवीन यादी पोस्ट करा', productName: 'उत्पाद / सेवेचे नाव', category: 'श्रेणी', price: 'किंमत', unit: 'एकक / कालावधी', sellerName: 'तुमचे नाव / दुकानाचे नाव', location: 'ठिकाण', whatsappNumber: 'WhatsApp मोबाइल नंबर', description: 'वर्णन', productImage: 'उत्पाद प्रतिमा', cancel: 'रद्द करा', postWithWhatsApp: 'WhatsApp सह पोस्ट करा', listingPosted: 'यादी पोस्ट झाली!', noListings: 'कोणतीही यादी आढळली नाही।' },
  seedGuide: { badge: 'बियाणे मार्गदर्शक', title: 'तुमच्या शेतासाठी योग्य बियाणे शोधा', subtitle: 'विविध प्रदेश, माती आणि हवामानासाठी अनुकूलित बियाण्यांचा संग्रह पहा।', recommendations: 'शिफारसी', calculator: 'बियाणे कॅल्क्युलेटर', catalog: 'संपूर्ण कॅटलॉग', searchPlaceholder: 'बियाणे शोधा...', season: 'हंगाम', allSeasons: 'सर्व हंगाम', clearFilters: 'फिल्टर साफ करा', noSeeds: 'तुमच्या निकषांशी जुळणारी बियाणे आढळली नाहीत।', fullCatalog: '🌱 संपूर्ण कॅटलॉग – बियाणे मार्गदर्शक', catalogSubtitle: 'तुमच्या सर्व शेती गरजांसाठी बियाण्यांचा संपूर्ण संग्रह', vegetables: '१. भाज्या', fruits: '२. फळे', flowers: '३. फुले', fieldCrops: '४. शेतातील पिके', growthDuration: 'वाढीचा कालावधी', climateSoil: 'हवामान/माती', yieldPotential: 'उत्पादन क्षमता', careTips: 'काळजी टिप्स' },
  ai: { badge: 'AI-चालित बुद्धिमत्ता', title: 'AI फार्म निर्णय इंजिन', subtitle: 'तुमच्या शेताचा तपशील भरा आणि संपूर्ण फार्म अहवाल मिळवा।', farmConditions: 'शेताची स्थिती', cropType: 'पिकाचा प्रकार', soilType: 'मातीचा प्रकार', cropStage: 'पिकाची अवस्था', season: 'हंगाम', irrigationSource: 'सिंचन स्रोत', stateRegion: 'राज्य / प्रदेश', farmArea: 'शेताचे क्षेत्रफळ (एकर)', temperature: 'तापमान', soilMoisture: 'मातीची आर्द्रता', generateReport: 'संपूर्ण फार्म अहवाल तयार करा', readyToAnalyze: 'विश्लेषणासाठी तयार', readySubtitle: 'AI-चालित माहितीसाठी शेताची स्थिती भरा।', cropOverview: 'पीक आढावा आणि मुख्य तथ्ये', irrigationPlan: 'सिंचन योजना', fertilizerSchedule: 'खत वेळापत्रक', pestRisk: 'कीड आणि रोग जोखीम मूल्यांकन', weeklyPlan: '७-दिवसांची कृती योजना', profitEstimate: 'नफा आणि महसूल अंदाज', govtSchemes: 'संबंधित सरकारी योजना', aiGenerated: 'AI जनित', missingFields: 'अपूर्ण फील्ड', missingFieldsDesc: 'कृपया पीक, माती, अवस्था आणि हंगाम भरा।', reportReady: 'फार्म अहवाल तयार' },
  common: { loading: 'लोड होत आहे...', search: 'शोधा', filter: 'फिल्टर', submit: 'सबमिट करा', cancel: 'रद्द करा', save: 'जतन करा', delete: 'हटवा', edit: 'संपादित करा', close: 'बंद करा', back: 'मागे', next: 'पुढे', previous: 'मागील', viewAll: 'सर्व पहा', learnMore: 'अधिक जाणून घ्या', getStarted: 'सुरू करा', required: 'आवश्यक', optional: 'पर्यायी', yes: 'होय', no: 'नाही', high: 'उच्च', medium: 'मध्यम', low: 'कमी', excellent: 'उत्कृष्ट', good: 'चांगले', fair: 'ठीक', poor: 'खराब' },
  footer: { tagline: 'AI-चालित माहिती आणि स्मार्ट शेती उपायांसह शेतकऱ्यांना सक्षम बनवणे।', quickLinks: 'जलद दुवे', features: 'वैशिष्ट्ये', rights: 'सर्व हक्क राखीव।' },
};
export default mr;
