import type { TranslationKeys } from './en';
const ne: TranslationKeys = {
  nav: { home: 'गृह', seedGuide: 'बीउ गाइड', weather: 'मौसम', aiTools: 'AI उपकरण', farmManagement: 'खेत व्यवस्थापन', community: 'समुदाय', sos: 'SOS', contact: 'सम्पर्क', login: 'लगइन', signup: 'साइन अप', logout: 'लगआउट', aiDecisionEngine: '🧠 AI निर्णय इन्जिन', voiceAssistant: '🎙️ भ्वाइस असिस्टेन्ट', profitPrediction: '📈 नाफा पूर्वानुमान', diseaseScanner: '🔬 रोग स्क्यानर', expenseTracker: '💰 खर्च ट्र्याकर', iotMonitoring: '📡 IoT अनुगमन', digitalTwin: '🗺️ डिजिटल ट्विन', farmerCommunity: '💬 किसान समुदाय', marketplace: '🛒 बजार', govtSchemes: '🏛️ सरकारी योजना', learningHub: '📚 सिकाइ केन्द्र', emergencySOS: '🚨 आपतकालीन SOS', switchTheme: 'थिम परिवर्तन' },
  hero: { badge: 'स्मार्ट कृषि प्लेटफर्म', title1: 'स्मार्ट खेती गर्नुहोस्,', title2: 'राम्रो फसल काट्नुहोस्', description: 'AgriAssist ले तपाईंको खेतमा अत्याधुनिक प्रविधि ल्याउँछ।', getStarted: 'सुरु गर्नुहोस्', exploreFeatures: 'सुविधाहरू हेर्नुहोस्', yieldIncrease: 'उत्पादन वृद्धि', costReduction: 'लागत कटौती', monitoring: 'अनुगमन' },
  features: { badge: 'शक्तिशाली सुविधाहरू', title: 'स्मार्ट खेतीका लागि सबै कुरा', subtitle: 'हाम्रो प्लेटफर्मले AI, IoT र डेटा विश्लेषण जोड्छ।' },
  cta: { title: 'आफ्नो खेती बदल्न तयार हुनुहुन्छ?', subtitle: 'हजारौं किसानहरूसँग जोडिनुहोस् जो AgriAssist प्रयोग गर्दैछन्।', startTrial: 'निःशुल्क ट्रायल सुरु गर्नुहोस्', scheduleDemo: 'डेमो तालिका बनाउनुहोस्' },
  weather: { title: 'कृषि मौसम पूर्वानुमान', subtitle: 'खेती-विशिष्ट अन्तर्दृष्टिसहित रियल-टाइम मौसम डेटा', searchPlaceholder: 'शहर वा स्थान खोज्नुहोस्...', current: 'हालको', forecast: 'पूर्वानुमान', calendar: 'पात्रो', humidity: 'आर्द्रता', wind: 'हावा', pressure: 'दबाब', visibility: 'दृश्यता', sunrise: 'सूर्योदय', sunset: 'सूर्यास्त', feelsLike: 'महसुस हुन्छ', uvIndex: 'UV सूचकांक', dewPoint: 'शीत बिन्दु', rainfall: 'वर्षा', farmingAdvisory: 'आजको खेती सल्लाह', noAlerts: 'कुनै सक्रिय अलर्ट छैन', weatherAlert: 'मौसम अलर्ट', forecastTitle: '१४-दिनको पूर्वानुमान', goodFarmDays: 'राम्रो खेती दिन', rainyDays: 'वर्षाका दिन', avgTemp: 'औसत तापमान', avgHumidity: 'औसत आर्द्रता' },
  marketplace: { badge: 'किसान बजार', title: 'फार्म मार्केटप्लेस र स्रोत साझेदारी', subtitle: 'बीउ, उपकरण, यन्त्र किन्नुहोस्/बेच्नुहोस्।', searchPlaceholder: 'बीउ, उपकरण, ट्र्याक्टर, मजदुर खोज्नुहोस्...', allCategories: 'सबै श्रेणीहरू', seeds: 'बीउ', tools: 'उपकरण', equipment: 'यन्त्र', labor: 'मजदुर', tractorRental: 'ट्र्याक्टर भाडा', postListing: 'सूची पोस्ट गर्नुहोस्', chatWhatsApp: 'WhatsApp मा च्याट गर्नुहोस्', contactSeller: 'विक्रेतासँग सम्पर्क गर्नुहोस्', soldOut: 'बिक्यो', whatsappAvailable: 'WhatsApp उपलब्ध', postNewListing: 'नयाँ सूची पोस्ट गर्नुहोस्', productName: 'उत्पाद / सेवाको नाम', category: 'श्रेणी', price: 'मूल्य', unit: 'एकाइ / अवधि', sellerName: 'तपाईंको नाम / पसलको नाम', location: 'स्थान', whatsappNumber: 'WhatsApp मोबाइल नम्बर', description: 'विवरण', productImage: 'उत्पाद छवि', cancel: 'रद्द गर्नुहोस्', postWithWhatsApp: 'WhatsApp सँग पोस्ट गर्नुहोस्', listingPosted: 'सूची पोस्ट भयो!', noListings: 'कुनै सूची फेला परेन।' },
  seedGuide: { badge: 'बीउ गाइड', title: 'आफ्नो खेतका लागि सही बीउ खोज्नुहोस्', subtitle: 'विभिन्न क्षेत्र, माटो र जलवायुका लागि अनुकूलित बीउहरूको संग्रह हेर्नुहोस्।', recommendations: 'सिफारिसहरू', calculator: 'बीउ क्याल्कुलेटर', catalog: 'पूर्ण क्याटलग', searchPlaceholder: 'बीउ खोज्नुहोस्...', season: 'मौसम', allSeasons: 'सबै मौसम', clearFilters: 'फिल्टर हटाउनुहोस्', noSeeds: 'तपाईंको मापदण्डसँग मेल खाने बीउ फेला परेन।', fullCatalog: '🌱 पूर्ण क्याटलग – बीउ गाइड', catalogSubtitle: 'तपाईंका सबै खेती आवश्यकताका लागि बीउहरूको पूर्ण संग्रह', vegetables: '१. तरकारीहरू', fruits: '२. फलफूल', flowers: '३. फूलहरू', fieldCrops: '४. खेतका बालीहरू', growthDuration: 'वृद्धि अवधि', climateSoil: 'जलवायु/माटो', yieldPotential: 'उत्पादन क्षमता', careTips: 'हेरचाह सुझावहरू' },
  ai: { badge: 'AI-संचालित बुद्धिमत्ता', title: 'AI फार्म निर्णय इन्जिन', subtitle: 'आफ्नो खेतको विवरण भर्नुहोस् र पूर्ण फार्म रिपोर्ट प्राप्त गर्नुहोस्।', farmConditions: 'खेतको अवस्था', cropType: 'बालीको प्रकार', soilType: 'माटोको प्रकार', cropStage: 'बाली अवस्था', season: 'मौसम', irrigationSource: 'सिँचाइ स्रोत', stateRegion: 'प्रदेश / क्षेत्र', farmArea: 'खेतको क्षेत्रफल (एकड)', temperature: 'तापमान', soilMoisture: 'माटोको आर्द्रता', generateReport: 'पूर्ण फार्म रिपोर्ट बनाउनुहोस्', readyToAnalyze: 'विश्लेषणका लागि तयार', readySubtitle: 'AI-संचालित अन्तर्दृष्टिका लागि खेतको अवस्था भर्नुहोस्।', cropOverview: 'बाली अवलोकन र मुख्य तथ्यहरू', irrigationPlan: 'सिँचाइ योजना', fertilizerSchedule: 'मल तालिका', pestRisk: 'कीरा र रोग जोखिम मूल्यांकन', weeklyPlan: '७-दिनको कार्य योजना', profitEstimate: 'नाफा र राजस्व अनुमान', govtSchemes: 'सम्बन्धित सरकारी योजनाहरू', aiGenerated: 'AI जनित', missingFields: 'अपूर्ण फिल्डहरू', missingFieldsDesc: 'कृपया बाली, माटो, अवस्था र मौसम भर्नुहोस्।', reportReady: 'फार्म रिपोर्ट तयार' },
  common: { loading: 'लोड हुँदैछ...', search: 'खोज्नुहोस्', filter: 'फिल्टर', submit: 'पेश गर्नुहोस्', cancel: 'रद्द गर्नुहोस्', save: 'सुरक्षित गर्नुहोस्', delete: 'मेटाउनुहोस्', edit: 'सम्पादन गर्नुहोस्', close: 'बन्द गर्नुहोस्', back: 'फिर्ता', next: 'अर्को', previous: 'अघिल्लो', viewAll: 'सबै हेर्नुहोस्', learnMore: 'थप जान्नुहोस्', getStarted: 'सुरु गर्नुहोस्', required: 'आवश्यक', optional: 'वैकल्पिक', yes: 'हो', no: 'होइन', high: 'उच्च', medium: 'मध्यम', low: 'कम', excellent: 'उत्कृष्ट', good: 'राम्रो', fair: 'ठीक', poor: 'खराब' },
  footer: { tagline: 'AI-संचालित अन्तर्दृष्टि र स्मार्ट कृषि समाधानहरूसँग किसानहरूलाई सशक्त बनाउँदै।', quickLinks: 'द्रुत लिंकहरू', features: 'सुविधाहरू', rights: 'सर्वाधिकार सुरक्षित।' },
};
export default ne;
