import type { TranslationKeys } from './en';
const ta: TranslationKeys = {
  nav: { home: 'முகப்பு', seedGuide: 'விதை வழிகாட்டி', weather: 'வானிலை', aiTools: 'AI கருவிகள்', farmManagement: 'பண்ணை மேலாண்மை', community: 'சமூகம்', sos: 'SOS', contact: 'தொடர்பு', login: 'உள்நுழை', signup: 'பதிவு செய்', logout: 'வெளியேறு', aiDecisionEngine: '🧠 AI முடிவு இயந்திரம்', voiceAssistant: '🎙️ குரல் உதவியாளர்', profitPrediction: '📈 லாப கணிப்பு', diseaseScanner: '🔬 நோய் ஸ்கேனர்', expenseTracker: '💰 செலவு கண்காணிப்பு', iotMonitoring: '📡 IoT கண்காணிப்பு', digitalTwin: '🗺️ டிஜிட்டல் இரட்டை', farmerCommunity: '💬 விவசாயி சமூகம்', marketplace: '🛒 சந்தை', govtSchemes: '🏛️ அரசு திட்டங்கள்', learningHub: '📚 கற்றல் மையம்', emergencySOS: '🚨 அவசர SOS', switchTheme: 'தீம் மாற்று' },
  hero: { badge: 'ஸ்மார்ட் விவசாய தளம்', title1: 'ஸ்மார்ட்டாக விவசாயம் செய்யுங்கள்,', title2: 'சிறந்த அறுவடை செய்யுங்கள்', description: 'AgriAssist உங்கள் வயல்களில் அதிநவீன தொழில்நுட்பத்தை கொண்டு வருகிறது।', getStarted: 'தொடங்குங்கள்', exploreFeatures: 'அம்சங்களை ஆராயுங்கள்', yieldIncrease: 'மகசூல் அதிகரிப்பு', costReduction: 'செலவு குறைப்பு', monitoring: 'கண்காணிப்பு' },
  features: { badge: 'சக்திவாய்ந்த அம்சங்கள்', title: 'ஸ்மார்ட் விவசாயத்திற்கு தேவையான அனைத்தும்', subtitle: 'எங்கள் தளம் AI, IoT மற்றும் தரவு பகுப்பாய்வை இணைக்கிறது।' },
  cta: { title: 'உங்கள் விவசாயத்தை மாற்ற தயாரா?', subtitle: 'AgriAssist பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் சேருங்கள்।', startTrial: 'இலவச சோதனை தொடங்குங்கள்', scheduleDemo: 'டெமோ திட்டமிடுங்கள்' },
  weather: { title: 'விவசாய வானிலை முன்னறிவிப்பு', subtitle: 'விவசாய-குறிப்பிட்ட நுண்ணறிவுடன் நிகழ்நேர வானிலை தரவு', searchPlaceholder: 'நகரம் அல்லது இடத்தை தேடுங்கள்...', current: 'தற்போதைய', forecast: 'முன்னறிவிப்பு', calendar: 'நாட்காட்டி', humidity: 'ஈரப்பதம்', wind: 'காற்று', pressure: 'அழுத்தம்', visibility: 'தெரிவுநிலை', sunrise: 'சூரிய உதயம்', sunset: 'சூரிய அஸ்தமனம்', feelsLike: 'உணர்கிறது', uvIndex: 'UV குறியீடு', dewPoint: 'பனி புள்ளி', rainfall: 'மழைப்பொழிவு', farmingAdvisory: 'இன்றைய விவசாய ஆலோசனை', noAlerts: 'செயலில் உள்ள எச்சரிக்கைகள் இல்லை', weatherAlert: 'வானிலை எச்சரிக்கை', forecastTitle: '14-நாள் முன்னறிவிப்பு', goodFarmDays: 'நல்ல விவசாய நாட்கள்', rainyDays: 'மழை நாட்கள்', avgTemp: 'சராசரி வெப்பநிலை', avgHumidity: 'சராசரி ஈரப்பதம்' },
  marketplace: { badge: 'விவசாயி சந்தை', title: 'பண்ணை சந்தை மற்றும் வள பகிர்வு', subtitle: 'விதைகள், கருவிகள், உபகரணங்கள் வாங்கவும்/விற்கவும்।', searchPlaceholder: 'விதைகள், கருவிகள், டிராக்டர், தொழிலாளர் தேடுங்கள்...', allCategories: 'அனைத்து வகைகளும்', seeds: 'விதைகள்', tools: 'கருவிகள்', equipment: 'உபகரணங்கள்', labor: 'தொழிலாளர்', tractorRental: 'டிராக்டர் வாடகை', postListing: 'பட்டியல் இடுங்கள்', chatWhatsApp: 'WhatsApp-ல் அரட்டை', contactSeller: 'விற்பனையாளரை தொடர்பு கொள்ளுங்கள்', soldOut: 'விற்றுவிட்டது', whatsappAvailable: 'WhatsApp கிடைக்கும்', postNewListing: 'புதிய பட்டியல் இடுங்கள்', productName: 'தயாரிப்பு / சேவையின் பெயர்', category: 'வகை', price: 'விலை', unit: 'அலகு / காலம்', sellerName: 'உங்கள் பெயர் / கடை பெயர்', location: 'இடம்', whatsappNumber: 'WhatsApp மொபைல் எண்', description: 'விளக்கம்', productImage: 'தயாரிப்பு படம்', cancel: 'ரத்து செய்', postWithWhatsApp: 'WhatsApp-உடன் இடுங்கள்', listingPosted: 'பட்டியல் இடப்பட்டது!', noListings: 'பட்டியல்கள் எதுவும் கிடைக்கவில்லை।' },
  seedGuide: { badge: 'விதை வழிகாட்டி', title: 'உங்கள் பண்ணைக்கு சரியான விதைகளை கண்டறியுங்கள்', subtitle: 'பல்வேறு பகுதிகள், மண் மற்றும் காலநிலைக்கு ஏற்ற விதைகளின் தொகுப்பை பாருங்கள்।', recommendations: 'பரிந்துரைகள்', calculator: 'விதை கணிப்பான்', catalog: 'முழு பட்டியல்', searchPlaceholder: 'விதைகளை தேடுங்கள்...', season: 'பருவம்', allSeasons: 'அனைத்து பருவங்களும்', clearFilters: 'வடிகட்டிகளை அழிக்கவும்', noSeeds: 'உங்கள் அளவுகோல்களுக்கு பொருந்தும் விதைகள் கிடைக்கவில்லை।', fullCatalog: '🌱 முழு பட்டியல் – விதை வழிகாட்டி', catalogSubtitle: 'உங்கள் அனைத்து விவசாய தேவைகளுக்கும் விதைகளின் முழு தொகுப்பு', vegetables: '1. காய்கறிகள்', fruits: '2. பழங்கள்', flowers: '3. பூக்கள்', fieldCrops: '4. வயல் பயிர்கள்', growthDuration: 'வளர்ச்சி காலம்', climateSoil: 'காலநிலை/மண்', yieldPotential: 'மகசூல் திறன்', careTips: 'பராமரிப்பு குறிப்புகள்' },
  ai: { badge: 'AI-இயக்கப்படும் நுண்ணறிவு', title: 'AI பண்ணை முடிவு இயந்திரம்', subtitle: 'உங்கள் பண்ணை விவரங்களை நிரப்பி முழு பண்ணை அறிக்கை பெறுங்கள்।', farmConditions: 'பண்ணை நிலைமைகள்', cropType: 'பயிர் வகை', soilType: 'மண் வகை', cropStage: 'பயிர் நிலை', season: 'பருவம்', irrigationSource: 'நீர்ப்பாசன ஆதாரம்', stateRegion: 'மாநிலம் / பகுதி', farmArea: 'பண்ணை பரப்பளவு (ஏக்கர்)', temperature: 'வெப்பநிலை', soilMoisture: 'மண் ஈரப்பதம்', generateReport: 'முழு பண்ணை அறிக்கை உருவாக்கு', readyToAnalyze: 'பகுப்பாய்வுக்கு தயார்', readySubtitle: 'AI-இயக்கப்படும் நுண்ணறிவுக்கு பண்ணை நிலைமைகளை நிரப்புங்கள்।', cropOverview: 'பயிர் கண்ணோட்டம் மற்றும் முக்கிய உண்மைகள்', irrigationPlan: 'நீர்ப்பாசன திட்டம்', fertilizerSchedule: 'உர அட்டவணை', pestRisk: 'பூச்சி மற்றும் நோய் ஆபத்து மதிப்பீடு', weeklyPlan: '7-நாள் செயல் திட்டம்', profitEstimate: 'லாபம் மற்றும் வருவாய் மதிப்பீடு', govtSchemes: 'தொடர்புடைய அரசு திட்டங்கள்', aiGenerated: 'AI உருவாக்கியது', missingFields: 'நிரப்பப்படாத புலங்கள்', missingFieldsDesc: 'தயவுசெய்து பயிர், மண், நிலை மற்றும் பருவம் நிரப்புங்கள்।', reportReady: 'பண்ணை அறிக்கை தயார்' },
  common: { loading: 'ஏற்றுகிறது...', search: 'தேடு', filter: 'வடிகட்டு', submit: 'சமர்ப்பி', cancel: 'ரத்து செய்', save: 'சேமி', delete: 'நீக்கு', edit: 'திருத்து', close: 'மூடு', back: 'பின்னால்', next: 'அடுத்து', previous: 'முந்தைய', viewAll: 'அனைத்தும் பார்', learnMore: 'மேலும் அறிக', getStarted: 'தொடங்குங்கள்', required: 'தேவையான', optional: 'விருப்பமான', yes: 'ஆம்', no: 'இல்லை', high: 'அதிக', medium: 'நடுத்தர', low: 'குறைந்த', excellent: 'சிறந்த', good: 'நல்ல', fair: 'சரியான', poor: 'மோசமான' },
  footer: { tagline: 'AI-இயக்கப்படும் நுண்ணறிவு மற்றும் ஸ்மார்ட் விவசாய தீர்வுகளுடன் விவசாயிகளை வலுப்படுத்துதல்।', quickLinks: 'விரைவு இணைப்புகள்', features: 'அம்சங்கள்', rights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை।' },
};
export default ta;
