import type { TranslationKeys } from './en';
const te: TranslationKeys = {
  nav: { home: 'హోమ్', seedGuide: 'విత్తన గైడ్', weather: 'వాతావరణం', aiTools: 'AI సాధనాలు', farmManagement: 'వ్యవసాయ నిర్వహణ', community: 'సమాజం', sos: 'SOS', contact: 'సంప్రదించండి', login: 'లాగిన్', signup: 'సైన్ అప్', logout: 'లాగ్అవుట్', aiDecisionEngine: '🧠 AI నిర్ణయ ఇంజిన్', voiceAssistant: '🎙️ వాయిస్ అసిస్టెంట్', profitPrediction: '📈 లాభం అంచనా', diseaseScanner: '🔬 వ్యాధి స్కానర్', expenseTracker: '💰 ఖర్చు ట్రాకర్', iotMonitoring: '📡 IoT పర్యవేక్షణ', digitalTwin: '🗺️ డిజిటల్ ట్విన్', farmerCommunity: '💬 రైతు సమాజం', marketplace: '🛒 మార్కెట్', govtSchemes: '🏛️ ప్రభుత్వ పథకాలు', learningHub: '📚 అభ్యాస కేంద్రం', emergencySOS: '🚨 అత్యవసర SOS', switchTheme: 'థీమ్ మార్చు' },
  hero: { badge: 'స్మార్ట్ వ్యవసాయ వేదిక', title1: 'స్మార్ట్‌గా వ్యవసాయం చేయండి,', title2: 'మెరుగైన పంట కోయండి', description: 'AgriAssist మీ పొలాలకు అత్యాధునిక సాంకేతికతను తీసుకువస్తుంది।', getStarted: 'ప్రారంభించండి', exploreFeatures: 'లక్షణాలు చూడండి', yieldIncrease: 'దిగుబడి పెరుగుదల', costReduction: 'ఖర్చు తగ్గింపు', monitoring: 'పర్యవేక్షణ' },
  features: { badge: 'శక్తివంతమైన లక్షణాలు', title: 'స్మార్ట్ వ్యవసాయానికి అవసరమైన అన్నీ', subtitle: 'మా వేదిక AI, IoT మరియు డేటా విశ్లేషణను కలుపుతుంది।' },
  cta: { title: 'మీ వ్యవసాయాన్ని మార్చడానికి సిద్ధంగా ఉన్నారా?', subtitle: 'AgriAssist ఉపయోగిస్తున్న వేలాది రైతులతో చేరండి।', startTrial: 'ఉచిత ట్రయల్ ప్రారంభించండి', scheduleDemo: 'డెమో షెడ్యూల్ చేయండి' },
  weather: { title: 'వ్యవసాయ వాతావరణ అంచనా', subtitle: 'వ్యవసాయ-నిర్దిష్ట అంతర్దృష్టితో రియల్-టైమ్ వాతావరణ డేటా', searchPlaceholder: 'నగరం లేదా స్థానం వెతకండి...', current: 'ప్రస్తుత', forecast: 'అంచనా', calendar: 'క్యాలెండర్', humidity: 'తేమ', wind: 'గాలి', pressure: 'పీడనం', visibility: 'దృశ్యమానత', sunrise: 'సూర్యోదయం', sunset: 'సూర్యాస్తమయం', feelsLike: 'అనిపిస్తుంది', uvIndex: 'UV సూచిక', dewPoint: 'మంచు బిందువు', rainfall: 'వర్షపాతం', farmingAdvisory: 'నేటి వ్యవసాయ సలహా', noAlerts: 'చురుకైన హెచ్చరికలు లేవు', weatherAlert: 'వాతావరణ హెచ్చరిక', forecastTitle: '14-రోజుల అంచనా', goodFarmDays: 'మంచి వ్యవసాయ రోజులు', rainyDays: 'వర్షపు రోజులు', avgTemp: 'సగటు ఉష్ణోగ్రత', avgHumidity: 'సగటు తేమ' },
  marketplace: { badge: 'రైతు మార్కెట్', title: 'ఫార్మ్ మార్కెట్‌ప్లేస్ మరియు వనరుల భాగస్వామ్యం', subtitle: 'విత్తనాలు, పరికరాలు, యంత్రాలు కొనండి/అమ్మండి।', searchPlaceholder: 'విత్తనాలు, పరికరాలు, ట్రాక్టర్, కూలీలు వెతకండి...', allCategories: 'అన్ని వర్గాలు', seeds: 'విత్తనాలు', tools: 'పరికరాలు', equipment: 'యంత్రాలు', labor: 'కూలీలు', tractorRental: 'ట్రాక్టర్ అద్దె', postListing: 'జాబితా పోస్ట్ చేయండి', chatWhatsApp: 'WhatsApp లో చాట్ చేయండి', contactSeller: 'విక్రేతను సంప్రదించండి', soldOut: 'అమ్ముడైంది', whatsappAvailable: 'WhatsApp అందుబాటులో ఉంది', postNewListing: 'కొత్త జాబితా పోస్ట్ చేయండి', productName: 'ఉత్పత్తి / సేవ పేరు', category: 'వర్గం', price: 'ధర', unit: 'యూనిట్ / వ్యవధి', sellerName: 'మీ పేరు / దుకాణం పేరు', location: 'స్థానం', whatsappNumber: 'WhatsApp మొబైల్ నంబర్', description: 'వివరణ', productImage: 'ఉత్పత్తి చిత్రం', cancel: 'రద్దు చేయండి', postWithWhatsApp: 'WhatsApp తో పోస్ట్ చేయండి', listingPosted: 'జాబితా పోస్ట్ అయింది!', noListings: 'జాబితాలు ఏవీ కనుగొనబడలేదు।' },
  seedGuide: { badge: 'విత్తన గైడ్', title: 'మీ పొలానికి సరైన విత్తనాలు కనుగొనండి', subtitle: 'వివిధ ప్రాంతాలు, నేల మరియు వాతావరణానికి అనుకూలమైన విత్తనాల సేకరణ చూడండి।', recommendations: 'సిఫార్సులు', calculator: 'విత్తన కాల్క్యులేటర్', catalog: 'పూర్తి కేటలాగ్', searchPlaceholder: 'విత్తనాలు వెతకండి...', season: 'సీజన్', allSeasons: 'అన్ని సీజన్లు', clearFilters: 'ఫిల్టర్లు క్లియర్ చేయండి', noSeeds: 'మీ ప్రమాణాలకు సరిపోయే విత్తనాలు కనుగొనబడలేదు।', fullCatalog: '🌱 పూర్తి కేటలాగ్ – విత్తన గైడ్', catalogSubtitle: 'మీ అన్ని వ్యవసాయ అవసరాలకు విత్తనాల పూర్తి సేకరణ', vegetables: '1. కూరగాయలు', fruits: '2. పండ్లు', flowers: '3. పూలు', fieldCrops: '4. పొలం పంటలు', growthDuration: 'పెరుగుదల వ్యవధి', climateSoil: 'వాతావరణం/నేల', yieldPotential: 'దిగుబడి సామర్థ్యం', careTips: 'సంరక్షణ చిట్కాలు' },
  ai: { badge: 'AI-ఆధారిత తెలివి', title: 'AI ఫార్మ్ నిర్ణయ ఇంజిన్', subtitle: 'మీ పొలం వివరాలు నింపండి మరియు పూర్తి ఫార్మ్ నివేదిక పొందండి।', farmConditions: 'పొలం పరిస్థితులు', cropType: 'పంట రకం', soilType: 'నేల రకం', cropStage: 'పంట దశ', season: 'సీజన్', irrigationSource: 'నీటిపారుదల మూలం', stateRegion: 'రాష్ట్రం / ప్రాంతం', farmArea: 'పొలం విస్తీర్ణం (ఎకరాలు)', temperature: 'ఉష్ణోగ్రత', soilMoisture: 'నేల తేమ', generateReport: 'పూర్తి ఫార్మ్ నివేదిక రూపొందించండి', readyToAnalyze: 'విశ్లేషణకు సిద్ధం', readySubtitle: 'AI-ఆధారిత అంతర్దృష్టి కోసం పొలం పరిస్థితులు నింపండి।', cropOverview: 'పంట అవలోకనం మరియు ముఖ్య వాస్తవాలు', irrigationPlan: 'నీటిపారుదల ప్రణాళిక', fertilizerSchedule: 'ఎరువు షెడ్యూల్', pestRisk: 'పురుగు మరియు వ్యాధి ప్రమాద మూల్యాంకనం', weeklyPlan: '7-రోజుల చర్య ప్రణాళిక', profitEstimate: 'లాభం మరియు ఆదాయం అంచనా', govtSchemes: 'సంబంధిత ప్రభుత్వ పథకాలు', aiGenerated: 'AI రూపొందించింది', missingFields: 'అసంపూర్ణ ఫీల్డ్‌లు', missingFieldsDesc: 'దయచేసి పంట, నేల, దశ మరియు సీజన్ నింపండి।', reportReady: 'ఫార్మ్ నివేదిక సిద్ధం' },
  common: { loading: 'లోడ్ అవుతోంది...', search: 'వెతకండి', filter: 'ఫిల్టర్', submit: 'సమర్పించండి', cancel: 'రద్దు చేయండి', save: 'సేవ్ చేయండి', delete: 'తొలగించండి', edit: 'సవరించండి', close: 'మూసివేయండి', back: 'వెనక్కి', next: 'తదుపరి', previous: 'మునుపటి', viewAll: 'అన్నీ చూడండి', learnMore: 'మరింత తెలుసుకోండి', getStarted: 'ప్రారంభించండి', required: 'అవసరం', optional: 'ఐచ్ఛికం', yes: 'అవును', no: 'కాదు', high: 'అధిక', medium: 'మధ్యస్థ', low: 'తక్కువ', excellent: 'అద్భుతం', good: 'మంచిది', fair: 'సరైనది', poor: 'చెడు' },
  footer: { tagline: 'AI-ఆధారిత అంతర్దృష్టి మరియు స్మార్ట్ వ్యవసాయ పరిష్కారాలతో రైతులను శక్తివంతం చేయడం।', quickLinks: 'త్వరిత లింక్‌లు', features: 'లక్షణాలు', rights: 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి।' },
};
export default te;
