import type { TranslationKeys } from './en';
const ur: TranslationKeys = {
  nav: { home: 'ہوم', seedGuide: 'بیج گائیڈ', weather: 'موسم', aiTools: 'AI ٹولز', farmManagement: 'کھیت انتظام', community: 'کمیونٹی', sos: 'SOS', contact: 'رابطہ', login: 'لاگ ان', signup: 'سائن اپ', logout: 'لاگ آؤٹ', aiDecisionEngine: '🧠 AI فیصلہ انجن', voiceAssistant: '🎙️ وائس اسسٹنٹ', profitPrediction: '📈 منافع پیشگوئی', diseaseScanner: '🔬 بیماری اسکینر', expenseTracker: '💰 اخراجات ٹریکر', iotMonitoring: '📡 IoT نگرانی', digitalTwin: '🗺️ ڈیجیٹل ٹوئن', farmerCommunity: '💬 کسان کمیونٹی', marketplace: '🛒 بازار', govtSchemes: '🏛️ سرکاری اسکیمیں', learningHub: '📚 سیکھنے کا مرکز', emergencySOS: '🚨 ہنگامی SOS', switchTheme: 'تھیم تبدیل کریں' },
  hero: { badge: 'سمارٹ زراعت پلیٹ فارم', title1: 'سمارٹ کھیتی کریں،', title2: 'بہتر فصل کاٹیں', description: 'AgriAssist آپ کے کھیتوں میں جدید ترین ٹیکنالوجی لاتا ہے۔', getStarted: 'شروع کریں', exploreFeatures: 'خصوصیات دیکھیں', yieldIncrease: 'پیداوار میں اضافہ', costReduction: 'لاگت میں کمی', monitoring: 'نگرانی' },
  features: { badge: 'طاقتور خصوصیات', title: 'سمارٹ کھیتی کے لیے سب کچھ', subtitle: 'ہمارا پلیٹ فارم AI، IoT اور ڈیٹا تجزیہ کو یکجا کرتا ہے۔' },
  cta: { title: 'اپنی کھیتی بدلنے کے لیے تیار ہیں؟', subtitle: 'ہزاروں کسانوں کے ساتھ شامل ہوں جو AgriAssist استعمال کر رہے ہیں۔', startTrial: 'مفت ٹرائل شروع کریں', scheduleDemo: 'ڈیمو شیڈول کریں' },
  weather: { title: 'زرعی موسم پیشگوئی', subtitle: 'کھیتی سے متعلق بصیرت کے ساتھ ریئل ٹائم موسم ڈیٹا', searchPlaceholder: 'شہر یا مقام تلاش کریں...', current: 'موجودہ', forecast: 'پیشگوئی', calendar: 'کیلنڈر', humidity: 'نمی', wind: 'ہوا', pressure: 'دباؤ', visibility: 'مرئیت', sunrise: 'طلوع آفتاب', sunset: 'غروب آفتاب', feelsLike: 'محسوس ہوتا ہے', uvIndex: 'UV انڈیکس', dewPoint: 'شبنم نقطہ', rainfall: 'بارش', farmingAdvisory: 'آج کی کھیتی مشاورت', noAlerts: 'کوئی فعال الرٹ نہیں', weatherAlert: 'موسم الرٹ', forecastTitle: '14 دن کی پیشگوئی', goodFarmDays: 'اچھے کھیتی دن', rainyDays: 'بارش کے دن', avgTemp: 'اوسط درجہ حرارت', avgHumidity: 'اوسط نمی' },
  marketplace: { badge: 'کسان بازار', title: 'فارم مارکیٹ پلیس اور وسائل کا اشتراک', subtitle: 'بیج، اوزار، آلات خریدیں/بیچیں۔', searchPlaceholder: 'بیج، اوزار، ٹریکٹر، مزدور تلاش کریں...', allCategories: 'تمام زمرے', seeds: 'بیج', tools: 'اوزار', equipment: 'آلات', labor: 'مزدور', tractorRental: 'ٹریکٹر کرایہ', postListing: 'فہرست پوسٹ کریں', chatWhatsApp: 'WhatsApp پر چیٹ کریں', contactSeller: 'بیچنے والے سے رابطہ کریں', soldOut: 'فروخت ہو گیا', whatsappAvailable: 'WhatsApp دستیاب', postNewListing: 'نئی فہرست پوسٹ کریں', productName: 'مصنوع / خدمت کا نام', category: 'زمرہ', price: 'قیمت', unit: 'اکائی / مدت', sellerName: 'آپ کا نام / دکان کا نام', location: 'مقام', whatsappNumber: 'WhatsApp موبائل نمبر', description: 'تفصیل', productImage: 'مصنوع کی تصویر', cancel: 'منسوخ کریں', postWithWhatsApp: 'WhatsApp کے ساتھ پوسٹ کریں', listingPosted: 'فہرست پوسٹ ہو گئی!', noListings: 'کوئی فہرست نہیں ملی۔' },
  seedGuide: { badge: 'بیج گائیڈ', title: 'اپنے کھیت کے لیے صحیح بیج تلاش کریں', subtitle: 'مختلف علاقوں، مٹی اور آب و ہوا کے لیے موزوں بیجوں کا مجموعہ دیکھیں۔', recommendations: 'سفارشات', calculator: 'بیج کیلکولیٹر', catalog: 'مکمل کیٹلاگ', searchPlaceholder: 'بیج تلاش کریں...', season: 'موسم', allSeasons: 'تمام موسم', clearFilters: 'فلٹر صاف کریں', noSeeds: 'آپ کے معیار سے مطابقت رکھنے والے بیج نہیں ملے۔', fullCatalog: '🌱 مکمل کیٹلاگ – بیج گائیڈ', catalogSubtitle: 'آپ کی تمام کھیتی ضروریات کے لیے بیجوں کا مکمل مجموعہ', vegetables: '1. سبزیاں', fruits: '2. پھل', flowers: '3. پھول', fieldCrops: '4. کھیت کی فصلیں', growthDuration: 'نشوونما کی مدت', climateSoil: 'آب و ہوا/مٹی', yieldPotential: 'پیداوار کی صلاحیت', careTips: 'دیکھ بھال کی تجاویز' },
  ai: { badge: 'AI سے چلنے والی ذہانت', title: 'AI فارم فیصلہ انجن', subtitle: 'اپنے کھیت کی تفصیلات بھریں اور مکمل فارم رپورٹ حاصل کریں۔', farmConditions: 'کھیت کے حالات', cropType: 'فصل کی قسم', soilType: 'مٹی کی قسم', cropStage: 'فصل کا مرحلہ', season: 'موسم', irrigationSource: 'آبپاشی کا ذریعہ', stateRegion: 'صوبہ / علاقہ', farmArea: 'کھیت کا رقبہ (ایکڑ)', temperature: 'درجہ حرارت', soilMoisture: 'مٹی کی نمی', generateReport: 'مکمل فارم رپورٹ بنائیں', readyToAnalyze: 'تجزیہ کے لیے تیار', readySubtitle: 'AI سے چلنے والی بصیرت کے لیے کھیت کے حالات بھریں۔', cropOverview: 'فصل کا جائزہ اور اہم حقائق', irrigationPlan: 'آبپاشی کا منصوبہ', fertilizerSchedule: 'کھاد کا شیڈول', pestRisk: 'کیڑے اور بیماری کے خطرے کا جائزہ', weeklyPlan: '7 دن کا عمل منصوبہ', profitEstimate: 'منافع اور آمدنی کا تخمینہ', govtSchemes: 'متعلقہ سرکاری اسکیمیں', aiGenerated: 'AI سے تیار', missingFields: 'نامکمل خانے', missingFieldsDesc: 'براہ کرم فصل، مٹی، مرحلہ اور موسم بھریں۔', reportReady: 'فارم رپورٹ تیار' },
  common: { loading: 'لوڈ ہو رہا ہے...', search: 'تلاش کریں', filter: 'فلٹر', submit: 'جمع کریں', cancel: 'منسوخ کریں', save: 'محفوظ کریں', delete: 'حذف کریں', edit: 'ترمیم کریں', close: 'بند کریں', back: 'واپس', next: 'اگلا', previous: 'پچھلا', viewAll: 'سب دیکھیں', learnMore: 'مزید جانیں', getStarted: 'شروع کریں', required: 'ضروری', optional: 'اختیاری', yes: 'ہاں', no: 'نہیں', high: 'زیادہ', medium: 'درمیانہ', low: 'کم', excellent: 'بہترین', good: 'اچھا', fair: 'ٹھیک', poor: 'خراب' },
  footer: { tagline: 'AI سے چلنے والی بصیرت اور سمارٹ زراعت حل کے ساتھ کسانوں کو بااختیار بنانا۔', quickLinks: 'فوری لنکس', features: 'خصوصیات', rights: 'تمام حقوق محفوظ ہیں۔' },
};
export default ur;
